# **ANALIKET**

Kaggle Repo: https://www.kaggle.com/patrickb1912/ipl-complete-dataset-20082020


### Liabraires

In [ ]:
import numpy as np
import pandas as pd

### Import Dataset Matches

In [ ]:
matches_sheet_id="1GLmJ5TFHSqgCoZExXVOi8_N0XUrPEb5HbjYdzgSSc7I"
matches_sheet_name="Matches"

matches= pd.read_csv("https://docs.google.com/spreadsheets/d/{}/gviz/tq?tqx=out:csv&sheet={}".format(matches_sheet_id,matches_sheet_name))

In [ ]:
matches

          id        city        date  ... method      umpire1         umpire2
0     335982   Bangalore  2008-04-18  ...    NaN    Asad Rauf     RE Koertzen
1     335983  Chandigarh  2008-04-19  ...    NaN    MR Benson      SL Shastri
2     335984       Delhi  2008-04-19  ...    NaN    Aleem Dar  GA Pratapkumar
3     335985      Mumbai  2008-04-20  ...    NaN     SJ Davis       DJ Harper
4     335986     Kolkata  2008-04-20  ...    NaN    BF Bowden     K Hariharan
..       ...         ...         ...  ...    ...          ...             ...
811  1216547       Dubai  2020-09-28  ...    NaN  Nitin Menon      PR Reiffel
812  1237177       Dubai  2020-11-05  ...    NaN  CB Gaffaney     Nitin Menon
813  1237178   Abu Dhabi  2020-11-06  ...    NaN   PR Reiffel          S Ravi
814  1237180   Abu Dhabi  2020-11-08  ...    NaN   PR Reiffel          S Ravi
815  1237181       Dubai  2020-11-10  ...    NaN  CB Gaffaney     Nitin Menon

[816 rows x 17 columns]

Import Dataset Deliveries

In [ ]:
deliveries_sheet_id="1q46D3MIMw_eAGN-17t9V8tTbjGDH0gHt_JHTWdSA_W8"
deliveries_sheet_name="Deliveries"

deliveries= pd.read_csv("https://docs.google.com/spreadsheets/d/{}/gviz/tq?tqx=out:csv&sheet={}".format(deliveries_sheet_id,deliveries_sheet_name))

In [ ]:
deliveries

             id  inning  ...           batting_team                 bowling_team
0        335982       1  ...  Kolkata Knight Riders  Royal Challengers Bangalore
1        335982       1  ...  Kolkata Knight Riders  Royal Challengers Bangalore
2        335982       1  ...  Kolkata Knight Riders  Royal Challengers Bangalore
3        335982       1  ...  Kolkata Knight Riders  Royal Challengers Bangalore
4        335982       1  ...  Kolkata Knight Riders  Royal Challengers Bangalore
...         ...     ...  ...                    ...                          ...
193463  1237181       1  ...         Delhi Capitals               Mumbai Indians
193464  1237181       1  ...         Delhi Capitals               Mumbai Indians
193465  1237181       1  ...         Delhi Capitals               Mumbai Indians
193466  1237181       1  ...         Delhi Capitals               Mumbai Indians
193467  1237181       1  ...         Delhi Capitals               Mumbai Indians

[193468 rows x 18 columns]

In [ ]:
matches['team1'].unique()

array(['Royal Challengers Bangalore', 'Kings XI Punjab',
       'Delhi Daredevils', 'Mumbai Indians', 'Kolkata Knight Riders',
       'Rajasthan Royals', 'Deccan Chargers', 'Chennai Super Kings',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Gujarat Lions', 'Rising Pune Supergiants',
       'Rising Pune Supergiant', 'Delhi Capitals'], dtype=object)

## **Data Cleaning and Preprocessing**

IPL Teams represents a city and if a city had been represented by multiple teams it should be count as as one. So, in order to apply this practice uniformly we are changing the team name to their cities

In [ ]:
matches_2=matches.copy()
team1=matches_2['team1'].unique()
matches_2['team1'].replace('Royal Challengers Bangalore','Bangalore',inplace=True)
matches_2['team1'].replace('Kings XI Punjab','Punjab',inplace=True)
matches_2['team1'].replace('Delhi Daredevils','Delhi',inplace=True)
matches_2['team1'].replace('Mumbai Indians','Mumbai',inplace=True)
matches_2['team1'].replace('Kolkata Knight Riders','Kolkata',inplace=True)
matches_2['team1'].replace('Rajasthan Royals','Rajasthan',inplace=True)
matches_2['team1'].replace('Deccan Chargers','Hyderabad',inplace=True)
matches_2['team1'].replace('Chennai Super Kings','Chennai',inplace=True)
matches_2['team1'].replace('Kochi Tuskers Kerala','Kerala',inplace=True)
matches_2['team1'].replace('Pune Warriors','Pune',inplace=True)
matches_2['team1'].replace('Sunrisers Hyderabad','Hyderabad',inplace=True)
matches_2['team1'].replace('Gujarat Lions','Gujarat',inplace=True)
matches_2['team1'].replace('Rising Pune Supergiants','Pune',inplace=True)
matches_2['team1'].replace('Rising Pune Supergiant','Pune',inplace=True)
matches_2['team1'].replace('Delhi Capitals','Delhi',inplace=True)

In [ ]:
matches_2['team1'].unique()

array(['Bangalore', 'Punjab', 'Delhi', 'Mumbai', 'Kolkata', 'Rajasthan',
       'Hyderabad', 'Chennai', 'Kerala', 'Pune', 'Gujarat'], dtype=object)

In [ ]:
team2=matches_2['team2'].unique()
print(team2)
matches_2['team2'].replace('Kolkata Knight Riders','Kolkata',inplace=True)
matches_2['team2'].replace('Chennai Super Kings','Chennai',inplace=True)
matches_2['team2'].replace('Rajasthan Royals','Rajasthan',inplace=True)
matches_2['team2'].replace('Royal Challengers Bangalore','Bangalore',inplace=True)
matches_2['team2'].replace('Deccan Chargers','Hyderabad',inplace=True)
matches_2['team2'].replace('Kings XI Punjab','Punjab',inplace=True)
matches_2['team2'].replace('Delhi Daredevils','Delhi',inplace=True)
matches_2['team2'].replace('Mumbai Indians','Mumbai',inplace=True)
matches_2['team2'].replace('Kochi Tuskers Kerala','Kerala',inplace=True)
matches_2['team2'].replace('Pune Warriors','Pune',inplace=True)
matches_2['team2'].replace('Sunrisers Hyderabad','Hyderabad',inplace=True)
matches_2['team2'].replace('Rising Pune Supergiants','Pune',inplace=True)
matches_2['team2'].replace('Gujarat Lions','Gujarat',inplace=True)
matches_2['team2'].replace('Rising Pune Supergiant','Pune',inplace=True)
matches_2['team2'].replace('Delhi Capitals','Delhi',inplace=True)

['Kolkata Knight Riders' 'Chennai Super Kings' 'Rajasthan Royals'
 'Royal Challengers Bangalore' 'Deccan Chargers' 'Kings XI Punjab'
 'Delhi Daredevils' 'Mumbai Indians' 'Kochi Tuskers Kerala'
 'Pune Warriors' 'Sunrisers Hyderabad' 'Rising Pune Supergiants'
 'Gujarat Lions' 'Rising Pune Supergiant' 'Delhi Capitals']

In [ ]:
matches_2['team2'].unique()

array(['Kolkata', 'Chennai', 'Rajasthan', 'Bangalore', 'Hyderabad',
       'Punjab', 'Delhi', 'Mumbai', 'Kerala', 'Pune', 'Gujarat'],
      dtype=object)

In [ ]:
matches_2.head(12)

        id        city        date  ... method    umpire1         umpire2
0   335982   Bangalore  2008-04-18  ...    NaN  Asad Rauf     RE Koertzen
1   335983  Chandigarh  2008-04-19  ...    NaN  MR Benson      SL Shastri
2   335984       Delhi  2008-04-19  ...    NaN  Aleem Dar  GA Pratapkumar
3   335985      Mumbai  2008-04-20  ...    NaN   SJ Davis       DJ Harper
4   335986     Kolkata  2008-04-20  ...    NaN  BF Bowden     K Hariharan
5   335987      Jaipur  2008-04-21  ...    NaN  Aleem Dar       RB Tiffin
6   335988   Hyderabad  2008-04-22  ...    NaN  IL Howell       AM Saheba
7   335989     Chennai  2008-04-23  ...    NaN  DJ Harper  GA Pratapkumar
8   335990   Hyderabad  2008-04-24  ...    NaN  Asad Rauf       MR Benson
9   335991  Chandigarh  2008-04-25  ...    NaN  Aleem Dar       AM Saheba
10  335992   Bangalore  2008-04-26  ...    NaN  MR Benson       IL Howell
11  335993     Chennai  2008-04-26  ...    NaN  BF Bowden  AV Jayaprakash

[12 rows x 17 columns]

In [ ]:
matches_2['winner'].unique()
matches_2['winner'].replace('Kolkata Knight Riders','Kolkata',inplace=True)
matches_2['winner'].replace('Chennai Super Kings','Chennai',inplace=True)
matches_2['winner'].replace('Delhi Daredevils','Delhi',inplace=True)
matches_2['winner'].replace('Royal Challengers Bangalore','Bangalore',inplace=True)
matches_2['winner'].replace('Rajasthan Royals','Rajasthan',inplace=True)
matches_2['winner'].replace('Kings XI Punjab','Punjab',inplace=True)
matches_2['winner'].replace('Deccan Chargers','Hyderabad',inplace=True)
matches_2['winner'].replace('Mumbai Indians','Mumbai',inplace=True)
matches_2['winner'].replace('Pune Warriors','Pune',inplace=True)
matches_2['winner'].replace('Kochi Tuskers Kerala','Kerala',inplace=True)
matches_2['winner'].replace('Sunrisers Hyderabad','Hyderabad',inplace=True)
matches_2['winner'].replace('Rising Pune Supergiants','Pune',inplace=True)
matches_2['winner'].replace('Gujarat Lions','Gujarat',inplace=True)
matches_2['winner'].replace('Rising Pune Supergiant','Delhi',inplace=True)
matches_2['winner'].replace('Delhi Capitals','Delhi',inplace=True)

In [ ]:
matches_2['winner'].fillna("No Result", inplace = True)

In [ ]:
matches_2['winner'].unique()

array(['Kolkata', 'Chennai', 'Delhi', 'Bangalore', 'Rajasthan', 'Punjab',
       'Hyderabad', 'Mumbai', 'Pune', 'Kerala', 'No Result', 'Gujarat'],
      dtype=object)

In [ ]:
matches_2.head(10)

       id        city        date  ... method    umpire1         umpire2
0  335982   Bangalore  2008-04-18  ...    NaN  Asad Rauf     RE Koertzen
1  335983  Chandigarh  2008-04-19  ...    NaN  MR Benson      SL Shastri
2  335984       Delhi  2008-04-19  ...    NaN  Aleem Dar  GA Pratapkumar
3  335985      Mumbai  2008-04-20  ...    NaN   SJ Davis       DJ Harper
4  335986     Kolkata  2008-04-20  ...    NaN  BF Bowden     K Hariharan
5  335987      Jaipur  2008-04-21  ...    NaN  Aleem Dar       RB Tiffin
6  335988   Hyderabad  2008-04-22  ...    NaN  IL Howell       AM Saheba
7  335989     Chennai  2008-04-23  ...    NaN  DJ Harper  GA Pratapkumar
8  335990   Hyderabad  2008-04-24  ...    NaN  Asad Rauf       MR Benson
9  335991  Chandigarh  2008-04-25  ...    NaN  Aleem Dar       AM Saheba

[10 rows x 17 columns]

In [ ]:
toss_winner=matches_2['toss_winner'].unique()
print(toss_winner)
matches_2['toss_winner'].replace('Royal Challengers Bangalore','Bangalore',inplace=True)
matches_2['toss_winner'].replace('Chennai Super Kings','Chennai',inplace=True)
matches_2['toss_winner'].replace('Rajasthan Royals','Rajasthan',inplace=True)
matches_2['toss_winner'].replace('Mumbai Indians','Mumbai',inplace=True)
matches_2['toss_winner'].replace('Deccan Chargers','Hyderabad',inplace=True)
matches_2['toss_winner'].replace('Kings XI Punjab','Punjab',inplace=True)
matches_2['toss_winner'].replace('Kolkata Knight Riders','Kolkata',inplace=True)
matches_2['toss_winner'].replace('Delhi Daredevils','Delhi',inplace=True)
matches_2['toss_winner'].replace('Kochi Tuskers Kerala','Kerala',inplace=True)
matches_2['toss_winner'].replace('Pune Warriors','Pune',inplace=True)
matches_2['toss_winner'].replace('Sunrisers Hyderabad','Hyderabad',inplace=True)
matches_2['toss_winner'].replace('Gujarat Lions','Gujarat',inplace=True)
matches_2['toss_winner'].replace('Rising Pune Supergiants','Pune',inplace=True)
matches_2['toss_winner'].replace('Rising Pune Supergiant','Pune',inplace=True)
matches_2['toss_winner'].replace('Delhi Capitals','Delhi',inplace=True)

['Royal Challengers Bangalore' 'Chennai Super Kings' 'Rajasthan Royals'
 'Mumbai Indians' 'Deccan Chargers' 'Kings XI Punjab'
 'Kolkata Knight Riders' 'Delhi Daredevils' 'Kochi Tuskers Kerala'
 'Pune Warriors' 'Sunrisers Hyderabad' 'Gujarat Lions'
 'Rising Pune Supergiants' 'Rising Pune Supergiant' 'Delhi Capitals']

In [ ]:
matches_2.head(10)

       id        city        date  ... method    umpire1         umpire2
0  335982   Bangalore  2008-04-18  ...    NaN  Asad Rauf     RE Koertzen
1  335983  Chandigarh  2008-04-19  ...    NaN  MR Benson      SL Shastri
2  335984       Delhi  2008-04-19  ...    NaN  Aleem Dar  GA Pratapkumar
3  335985      Mumbai  2008-04-20  ...    NaN   SJ Davis       DJ Harper
4  335986     Kolkata  2008-04-20  ...    NaN  BF Bowden     K Hariharan
5  335987      Jaipur  2008-04-21  ...    NaN  Aleem Dar       RB Tiffin
6  335988   Hyderabad  2008-04-22  ...    NaN  IL Howell       AM Saheba
7  335989     Chennai  2008-04-23  ...    NaN  DJ Harper  GA Pratapkumar
8  335990   Hyderabad  2008-04-24  ...    NaN  Asad Rauf       MR Benson
9  335991  Chandigarh  2008-04-25  ...    NaN  Aleem Dar       AM Saheba

[10 rows x 17 columns]

In [ ]:
matches_2['city'].unique()

array(['Bangalore', 'Chandigarh', 'Delhi', 'Mumbai', 'Kolkata', 'Jaipur',
       'Hyderabad', 'Chennai', 'Cape Town', 'Port Elizabeth', 'Durban',
       'Centurion', 'East London', 'Johannesburg', 'Kimberley',
       'Bloemfontein', 'Ahmedabad', 'Cuttack', 'Nagpur', 'Dharamsala',
       'Kochi', 'Indore', 'Visakhapatnam', 'Pune', 'Raipur', 'Ranchi',
       'Abu Dhabi', nan, 'Rajkot', 'Kanpur', 'Bengaluru', 'Dubai',
       'Sharjah'], dtype=object)

In [ ]:
matches_2['city'].replace('Bengaluru','Bangalore',inplace=True)
matches_2['city'].fillna("Unknown City", inplace = True)
matches_2['city'].unique()

array(['Bangalore', 'Chandigarh', 'Delhi', 'Mumbai', 'Kolkata', 'Jaipur',
       'Hyderabad', 'Chennai', 'Cape Town', 'Port Elizabeth', 'Durban',
       'Centurion', 'East London', 'Johannesburg', 'Kimberley',
       'Bloemfontein', 'Ahmedabad', 'Cuttack', 'Nagpur', 'Dharamsala',
       'Kochi', 'Indore', 'Visakhapatnam', 'Pune', 'Raipur', 'Ranchi',
       'Abu Dhabi', 'Unknown City', 'Rajkot', 'Kanpur', 'Dubai',
       'Sharjah'], dtype=object)

In [ ]:
matches_2.head()

       id        city        date  ... method    umpire1         umpire2
0  335982   Bangalore  2008-04-18  ...    NaN  Asad Rauf     RE Koertzen
1  335983  Chandigarh  2008-04-19  ...    NaN  MR Benson      SL Shastri
2  335984       Delhi  2008-04-19  ...    NaN  Aleem Dar  GA Pratapkumar
3  335985      Mumbai  2008-04-20  ...    NaN   SJ Davis       DJ Harper
4  335986     Kolkata  2008-04-20  ...    NaN  BF Bowden     K Hariharan

[5 rows x 17 columns]

In [ ]:
matches_2['eliminator'].unique()

array(['N', 'Y', nan], dtype=object)

In [ ]:

matches_2['eliminator'].replace('N','No',inplace=True)
matches_2['eliminator'].replace('Y','Yes',inplace=True)
matches_2['eliminator'].fillna("NR", inplace = True)

In [ ]:
matches_2['eliminator'].unique()

array(['No', 'Yes', 'NR'], dtype=object)

In [ ]:
matches_2['player_of_match'].unique()

array(['BB McCullum', 'MEK Hussey', 'MF Maharoof', 'MV Boucher',
       'DJ Hussey', 'SR Watson', 'V Sehwag', 'ML Hayden', 'YK Pathan',
       'KC Sangakkara', 'JDP Oram', 'AC Gilchrist', 'SM Katich',
       'MS Dhoni', 'ST Jayasuriya', 'GD McGrath', 'SE Marsh',
       'SA Asnodkar', 'R Vinay Kumar', 'IK Pathan', 'SM Pollock',
       'Sohail Tanvir', 'S Sreesanth', 'A Nehra', 'SC Ganguly',
       'CRD Fernando', 'L Balaji', 'Shoaib Akhtar', 'A Mishra',
       'DPMD Jayawardene', 'GC Smith', 'DJ Bravo', 'M Ntini',
       'SP Goswami', 'A Kumble', 'KD Karthik', 'JA Morkel', 'P Kumar',
       'Umar Gul', 'SK Raina', 'SR Tendulkar', 'R Dravid', 'DL Vettori',
       'RP Singh', 'M Muralitharan', 'CH Gayle', 'AB de Villiers',
       'RS Bopara', 'PP Ojha', 'TM Dilshan', 'HH Gibbs', 'DP Nannes',
       'JP Duminy', 'Yuvraj Singh', 'SB Jakati', 'JH Kallis', 'G Gambhir',
       'RG Sharma', 'A Singh', 'S Badrinath', 'DR Smith', 'LRPL Taylor',
       'Harbhajan Singh', 'R Bhatia', 'SK Warne', 'B Lee', 'BJ Hodge',
       'LR Shukla', 'MK Pandey', 'AD Mathews', 'MK Tiwary', 'WPUJC Vaas',
       'A Symonds', 'AA Jhunjhunwala', 'J Theron', 'RV Uthappa',
       'AC Voges', 'KM Jadhav', 'NV Ojha', 'DA Warner', 'SL Malinga',
       'M Vijay', 'KP Pietersen', 'AT Rayudu', 'PD Collingwood',
       'MJ Lumb', 'TL Suman', 'RJ Harris', 'PP Chawla', 'Harmeet Singh',
       'KA Pollard', 'R Ashwin', 'R McLaren', 'JD Unadkat', 'M Kartik',
       'DE Bollinger', 'S Anirudha', 'SK Trivedi', 'SB Wagh',
       'PC Valthaty', 'MD Mishra', 'DW Steyn', 'S Sohal', 'MM Patel',
       'V Kohli', 'I Sharma', 'J Botha', 'Iqbal Abdulla',
       'P Parameswaran', 'R Sharma', 'MR Marsh', 'BA Bhatt', 'S Aravind',
       'WP Saha', 'S Dhawan', nan, 'JEC Franklin', 'RE Levi', 'SPD Smith',
       'AM Rahane', 'RA Jadeja', 'MN Samuels', 'M Morkel', 'F du Plessis',
       'AD Mascarenhas', 'Shakib Al Hasan', 'JD Ryder', 'SP Narine',
       'S Nadeem', 'KMDN Kulasekara', 'CL White', 'Mandeep Singh',
       'P Negi', 'Azhar Mahmood', 'BW Hilfenhaus', 'A Chandila',
       'UT Yadav', 'MS Bisla', 'M Vohra', 'GH Vihari', 'AJ Finch',
       'JP Faulkner', 'MS Gony', 'DA Miller', 'SV Samson', 'DJG Sammy',
       'MG Johnson', 'KK Cooper', 'PA Patel', 'AP Tare', 'LJ Wright',
       'YS Chahal', 'GJ Maxwell', 'CA Lynn', 'MM Sharma', 'PV Tambe',
       'Sandeep Sharma', 'B Kumar', 'CJ Anderson', 'KK Nair', 'AR Patel',
       'LMP Simmons', 'DJ Hooda', 'GJ Bailey', 'AD Russell', 'MA Agarwal',
       'SS Iyer', 'MA Starc', 'VR Aaron', 'TA Boult', 'NM Coulter-Nile',
       'EJG Morgan', 'HH Pandya', 'MC Henriques', 'Z Khan',
       'MJ McClenaghan', 'Q de Kock', 'Mustafizur Rahman', 'SA Yadav',
       'AB Dinda', 'CH Morris', 'CR Brathwaite', 'RR Pant', 'MP Stoinis',
       'A Zampa', 'KH Pandya', 'HM Amla', 'BCJ Cutting', 'Rashid Khan',
       'N Rana', 'JJ Bumrah', 'AJ Tye', 'BA Stokes', 'KS Williamson',
       'JC Buttler', 'LH Ferguson', 'Mohammed Shami', 'RA Tripathi',
       'Mohammed Siraj', 'HV Patel', 'Washington Sundar', 'KV Sharma',
       'KL Rahul', 'SW Billings', 'JJ Roy', 'B Stanlake', 'JC Archer',
       'AS Rajpoot', 'TG Southee', 'Mujeeb Ur Rahman', 'Ishan Kishan',
       'Kuldeep Yadav', 'S Gopal', 'L Ngidi', 'PP Shaw', 'JM Bairstow',
       'SM Curran', 'AS Joseph', 'K Rabada', 'HF Gurney', 'DL Chahar',
       'Imran Tahir', 'KMA Paul', 'KK Ahmed', 'Shubman Gill',
       'SO Hetmyer', 'CV Varun', 'CJ Jordan', 'Shivam Mavi', 'A Nortje',
       'RD Gaikwad', 'R Tewatia', 'PK Garg', 'PJ Cummins'], dtype=object)

In [ ]:
matches_2['player_of_match'].isnull().unique()

array([False,  True])

In [ ]:
matches_2['player_of_match'].fillna("No Result", inplace = True)

In [ ]:
matches_2['player_of_match'].unique()

array(['BB McCullum', 'MEK Hussey', 'MF Maharoof', 'MV Boucher',
       'DJ Hussey', 'SR Watson', 'V Sehwag', 'ML Hayden', 'YK Pathan',
       'KC Sangakkara', 'JDP Oram', 'AC Gilchrist', 'SM Katich',
       'MS Dhoni', 'ST Jayasuriya', 'GD McGrath', 'SE Marsh',
       'SA Asnodkar', 'R Vinay Kumar', 'IK Pathan', 'SM Pollock',
       'Sohail Tanvir', 'S Sreesanth', 'A Nehra', 'SC Ganguly',
       'CRD Fernando', 'L Balaji', 'Shoaib Akhtar', 'A Mishra',
       'DPMD Jayawardene', 'GC Smith', 'DJ Bravo', 'M Ntini',
       'SP Goswami', 'A Kumble', 'KD Karthik', 'JA Morkel', 'P Kumar',
       'Umar Gul', 'SK Raina', 'SR Tendulkar', 'R Dravid', 'DL Vettori',
       'RP Singh', 'M Muralitharan', 'CH Gayle', 'AB de Villiers',
       'RS Bopara', 'PP Ojha', 'TM Dilshan', 'HH Gibbs', 'DP Nannes',
       'JP Duminy', 'Yuvraj Singh', 'SB Jakati', 'JH Kallis', 'G Gambhir',
       'RG Sharma', 'A Singh', 'S Badrinath', 'DR Smith', 'LRPL Taylor',
       'Harbhajan Singh', 'R Bhatia', 'SK Warne', 'B Lee', 'BJ Hodge',
       'LR Shukla', 'MK Pandey', 'AD Mathews', 'MK Tiwary', 'WPUJC Vaas',
       'A Symonds', 'AA Jhunjhunwala', 'J Theron', 'RV Uthappa',
       'AC Voges', 'KM Jadhav', 'NV Ojha', 'DA Warner', 'SL Malinga',
       'M Vijay', 'KP Pietersen', 'AT Rayudu', 'PD Collingwood',
       'MJ Lumb', 'TL Suman', 'RJ Harris', 'PP Chawla', 'Harmeet Singh',
       'KA Pollard', 'R Ashwin', 'R McLaren', 'JD Unadkat', 'M Kartik',
       'DE Bollinger', 'S Anirudha', 'SK Trivedi', 'SB Wagh',
       'PC Valthaty', 'MD Mishra', 'DW Steyn', 'S Sohal', 'MM Patel',
       'V Kohli', 'I Sharma', 'J Botha', 'Iqbal Abdulla',
       'P Parameswaran', 'R Sharma', 'MR Marsh', 'BA Bhatt', 'S Aravind',
       'WP Saha', 'S Dhawan', 'No Result', 'JEC Franklin', 'RE Levi',
       'SPD Smith', 'AM Rahane', 'RA Jadeja', 'MN Samuels', 'M Morkel',
       'F du Plessis', 'AD Mascarenhas', 'Shakib Al Hasan', 'JD Ryder',
       'SP Narine', 'S Nadeem', 'KMDN Kulasekara', 'CL White',
       'Mandeep Singh', 'P Negi', 'Azhar Mahmood', 'BW Hilfenhaus',
       'A Chandila', 'UT Yadav', 'MS Bisla', 'M Vohra', 'GH Vihari',
       'AJ Finch', 'JP Faulkner', 'MS Gony', 'DA Miller', 'SV Samson',
       'DJG Sammy', 'MG Johnson', 'KK Cooper', 'PA Patel', 'AP Tare',
       'LJ Wright', 'YS Chahal', 'GJ Maxwell', 'CA Lynn', 'MM Sharma',
       'PV Tambe', 'Sandeep Sharma', 'B Kumar', 'CJ Anderson', 'KK Nair',
       'AR Patel', 'LMP Simmons', 'DJ Hooda', 'GJ Bailey', 'AD Russell',
       'MA Agarwal', 'SS Iyer', 'MA Starc', 'VR Aaron', 'TA Boult',
       'NM Coulter-Nile', 'EJG Morgan', 'HH Pandya', 'MC Henriques',
       'Z Khan', 'MJ McClenaghan', 'Q de Kock', 'Mustafizur Rahman',
       'SA Yadav', 'AB Dinda', 'CH Morris', 'CR Brathwaite', 'RR Pant',
       'MP Stoinis', 'A Zampa', 'KH Pandya', 'HM Amla', 'BCJ Cutting',
       'Rashid Khan', 'N Rana', 'JJ Bumrah', 'AJ Tye', 'BA Stokes',
       'KS Williamson', 'JC Buttler', 'LH Ferguson', 'Mohammed Shami',
       'RA Tripathi', 'Mohammed Siraj', 'HV Patel', 'Washington Sundar',
       'KV Sharma', 'KL Rahul', 'SW Billings', 'JJ Roy', 'B Stanlake',
       'JC Archer', 'AS Rajpoot', 'TG Southee', 'Mujeeb Ur Rahman',
       'Ishan Kishan', 'Kuldeep Yadav', 'S Gopal', 'L Ngidi', 'PP Shaw',
       'JM Bairstow', 'SM Curran', 'AS Joseph', 'K Rabada', 'HF Gurney',
       'DL Chahar', 'Imran Tahir', 'KMA Paul', 'KK Ahmed', 'Shubman Gill',
       'SO Hetmyer', 'CV Varun', 'CJ Jordan', 'Shivam Mavi', 'A Nortje',
       'RD Gaikwad', 'R Tewatia', 'PK Garg', 'PJ Cummins'], dtype=object)

In [ ]:
matches_2.head()

       id        city        date  ... method    umpire1         umpire2
0  335982   Bangalore  2008-04-18  ...    NaN  Asad Rauf     RE Koertzen
1  335983  Chandigarh  2008-04-19  ...    NaN  MR Benson      SL Shastri
2  335984       Delhi  2008-04-19  ...    NaN  Aleem Dar  GA Pratapkumar
3  335985      Mumbai  2008-04-20  ...    NaN   SJ Davis       DJ Harper
4  335986     Kolkata  2008-04-20  ...    NaN  BF Bowden     K Hariharan

[5 rows x 17 columns]

In [ ]:
matches_2['venue'].isnull().unique()

array([False])

In [ ]:
matches_2['venue'].unique()

array(['M Chinnaswamy Stadium',
       'Punjab Cricket Association Stadium, Mohali', 'Feroz Shah Kotla',
       'Wankhede Stadium', 'Eden Gardens', 'Sawai Mansingh Stadium',
       'Rajiv Gandhi International Stadium, Uppal',
       'MA Chidambaram Stadium, Chepauk', 'Dr DY Patil Sports Academy',
       'Newlands', "St George's Park", 'Kingsmead', 'SuperSport Park',
       'Buffalo Park', 'New Wanderers Stadium', 'De Beers Diamond Oval',
       'OUTsurance Oval', 'Brabourne Stadium',
       'Sardar Patel Stadium, Motera', 'Barabati Stadium',
       'Vidarbha Cricket Association Stadium, Jamtha',
       'Himachal Pradesh Cricket Association Stadium', 'Nehru Stadium',
       'Holkar Cricket Stadium',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Subrata Roy Sahara Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'JSCA International Stadium Complex', 'Sheikh Zayed Stadium',
       'Sharjah Cricket Stadium', 'Dubai International Cricket Stadium',
       'Maharashtra Cricket Association Stadium',
       'Punjab Cricket Association IS Bindra Stadium, Mohali',
       'Saurashtra Cricket Association Stadium', 'Green Park',
       'M.Chinnaswamy Stadium'], dtype=object)

In [ ]:
matches_2['venue'].replace('M Chinnaswamy Stadium','M.Chinnaswamy Stadium',inplace=True)
matches_2['venue'].replace('Punjab Cricket Association IS Bindra Stadium, Mohali','Punjab Cricket Association IS Bindra Stadium',inplace=True)
matches_2['venue'].replace('Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium','DYSRR International Cricket Stadium',inplace=True)

In [ ]:
matches_2['venue'].unique()

array(['M.Chinnaswamy Stadium',
       'Punjab Cricket Association Stadium, Mohali', 'Feroz Shah Kotla',
       'Wankhede Stadium', 'Eden Gardens', 'Sawai Mansingh Stadium',
       'Rajiv Gandhi International Stadium, Uppal',
       'MA Chidambaram Stadium, Chepauk', 'Dr DY Patil Sports Academy',
       'Newlands', "St George's Park", 'Kingsmead', 'SuperSport Park',
       'Buffalo Park', 'New Wanderers Stadium', 'De Beers Diamond Oval',
       'OUTsurance Oval', 'Brabourne Stadium',
       'Sardar Patel Stadium, Motera', 'Barabati Stadium',
       'Vidarbha Cricket Association Stadium, Jamtha',
       'Himachal Pradesh Cricket Association Stadium', 'Nehru Stadium',
       'Holkar Cricket Stadium', 'DYSRR International Cricket Stadium',
       'Subrata Roy Sahara Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'JSCA International Stadium Complex', 'Sheikh Zayed Stadium',
       'Sharjah Cricket Stadium', 'Dubai International Cricket Stadium',
       'Maharashtra Cricket Association Stadium',
       'Punjab Cricket Association IS Bindra Stadium',
       'Saurashtra Cricket Association Stadium', 'Green Park'],
      dtype=object)

In [ ]:
matches_2['neutral_venue'].unique()

array([0, 1])

In [ ]:
matches_2['result'].unique()

array(['runs', 'wickets', 'tie', nan], dtype=object)

In [ ]:
matches_2['result_margin'].unique()

array([140.,  33.,   9.,   5.,   6.,   3.,  66.,   7.,  10.,   4.,  13.,
        45.,   8.,  29.,  18.,  23.,  41.,  12.,  65.,  25.,   1.,  14.,
       105.,  19.,  75.,  92.,  11.,  24.,  nan,  27.,  38.,  78.,  16.,
        53.,   2.,  31.,  55.,  98.,  34.,  36.,  39.,  17.,  40.,  67.,
        63.,  37.,  57.,  35.,  22.,  21.,  48.,  26.,  20.,  85.,  32.,
        76., 111.,  82.,  43.,  58.,  28.,  74.,  42.,  59.,  46.,  47.,
        86.,  44.,  87., 130.,  15.,  60.,  77.,  30.,  50.,  93.,  72.,
        62.,  97., 138.,  71., 144.,  80.,  51.,  61., 146.,  64., 102.,
       118.,  49.,  88.,  69.])

In [ ]:
matches_2['result_margin'].isnull().unique()

array([False,  True])

In [ ]:
matches_2['result_margin'].fillna(0, inplace = True)

In [ ]:
matches_2['result_margin'].isnull().unique()

array([False])

In [ ]:
matches_2.head()

       id        city        date  ... method    umpire1         umpire2
0  335982   Bangalore  2008-04-18  ...    NaN  Asad Rauf     RE Koertzen
1  335983  Chandigarh  2008-04-19  ...    NaN  MR Benson      SL Shastri
2  335984       Delhi  2008-04-19  ...    NaN  Aleem Dar  GA Pratapkumar
3  335985      Mumbai  2008-04-20  ...    NaN   SJ Davis       DJ Harper
4  335986     Kolkata  2008-04-20  ...    NaN  BF Bowden     K Hariharan

[5 rows x 17 columns]

In [ ]:
matches_2['eliminator'].isnull().unique()

array([False])

In [ ]:
matches_2['method'].unique()

array([nan, 'D/L'], dtype=object)

In [ ]:
matches_2['method'].fillna("Normal", inplace = True)

In [ ]:
matches_2.head()

       id        city        date  ...  method    umpire1         umpire2
0  335982   Bangalore  2008-04-18  ...  Normal  Asad Rauf     RE Koertzen
1  335983  Chandigarh  2008-04-19  ...  Normal  MR Benson      SL Shastri
2  335984       Delhi  2008-04-19  ...  Normal  Aleem Dar  GA Pratapkumar
3  335985      Mumbai  2008-04-20  ...  Normal   SJ Davis       DJ Harper
4  335986     Kolkata  2008-04-20  ...  Normal  BF Bowden     K Hariharan

[5 rows x 17 columns]

In [ ]:
matches_2['umpire1'].isnull().unique()

array([False])

In [ ]:
matches_2['umpire2'].isnull().unique()

array([False])

In [ ]:
deliveries_2 = deliveries.copy()
deliveries_2.head()

       id  inning  ...           batting_team                 bowling_team
0  335982       1  ...  Kolkata Knight Riders  Royal Challengers Bangalore
1  335982       1  ...  Kolkata Knight Riders  Royal Challengers Bangalore
2  335982       1  ...  Kolkata Knight Riders  Royal Challengers Bangalore
3  335982       1  ...  Kolkata Knight Riders  Royal Challengers Bangalore
4  335982       1  ...  Kolkata Knight Riders  Royal Challengers Bangalore

[5 rows x 18 columns]

In [ ]:
deliveries_2['batting_team'].unique()

array(['Kolkata Knight Riders', 'Royal Challengers Bangalore',
       'Kings XI Punjab', 'Chennai Super Kings', 'Rajasthan Royals',
       'Delhi Daredevils', 'Mumbai Indians', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals'], dtype=object)

In [ ]:
deliveries_2['batting_team'].replace('Royal Challengers Bangalore','Bangalore',inplace=True)
deliveries_2['batting_team'].replace('Chennai Super Kings','Chennai',inplace=True)
deliveries_2['batting_team'].replace('Rajasthan Royals','Rajasthan',inplace=True)
deliveries_2['batting_team'].replace('Mumbai Indians','Mumbai',inplace=True)
deliveries_2['batting_team'].replace('Deccan Chargers','Hyderabad',inplace=True)
deliveries_2['batting_team'].replace('Kings XI Punjab','Punjab',inplace=True)
deliveries_2['batting_team'].replace('Kolkata Knight Riders','Kolkata',inplace=True)
deliveries_2['batting_team'].replace('Delhi Daredevils','Delhi',inplace=True)
deliveries_2['batting_team'].replace('Kochi Tuskers Kerala','Kerala',inplace=True)
deliveries_2['batting_team'].replace('Pune Warriors','Pune',inplace=True)
deliveries_2['batting_team'].replace('Sunrisers Hyderabad','Hyderabad',inplace=True)
deliveries_2['batting_team'].replace('Gujarat Lions','Gujarat',inplace=True)
deliveries_2['batting_team'].replace('Rising Pune Supergiants','Pune',inplace=True)
deliveries_2['batting_team'].replace('Rising Pune Supergiant','Pune',inplace=True)
deliveries_2['batting_team'].replace('Delhi Capitals','Delhi',inplace=True)

In [ ]:
deliveries_2['batting_team'].unique()

array(['Kolkata', 'Bangalore', 'Punjab', 'Chennai', 'Rajasthan', 'Delhi',
       'Mumbai', 'Hyderabad', 'Kerala', 'Pune', 'Gujarat'], dtype=object)

In [ ]:
deliveries_2['batting_team'].isnull().unique()

array([False])

In [ ]:
deliveries_2['bowling_team'].unique()

array(['Royal Challengers Bangalore', 'Kolkata Knight Riders',
       'Chennai Super Kings', 'Kings XI Punjab', 'Delhi Daredevils',
       'Rajasthan Royals', 'Mumbai Indians', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', nan,
       'Sunrisers Hyderabad', 'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals'], dtype=object)

In [ ]:
deliveries_2['bowling_team'].replace('Royal Challengers Bangalore','Bangalore',inplace=True)
deliveries_2['bowling_team'].replace('Chennai Super Kings','Chennai',inplace=True)
deliveries_2['bowling_team'].replace('Rajasthan Royals','Rajasthan',inplace=True)
deliveries_2['bowling_team'].replace('Mumbai Indians','Mumbai',inplace=True)
deliveries_2['bowling_team'].replace('Deccan Chargers','Hyderabad',inplace=True)
deliveries_2['bowling_team'].replace('Kings XI Punjab','Punjab',inplace=True)
deliveries_2['bowling_team'].replace('Kolkata Knight Riders','Kolkata',inplace=True)
deliveries_2['bowling_team'].replace('Delhi Daredevils','Delhi',inplace=True)
deliveries_2['bowling_team'].replace('Kochi Tuskers Kerala','Kerala',inplace=True)
deliveries_2['bowling_team'].replace('Pune Warriors','Pune',inplace=True)
deliveries_2['bowling_team'].replace('Sunrisers Hyderabad','Hyderabad',inplace=True)
deliveries_2['bowling_team'].replace('Gujarat Lions','Gujarat',inplace=True)
deliveries_2['bowling_team'].replace('Rising Pune Supergiants','Pune',inplace=True)
deliveries_2['bowling_team'].replace('Rising Pune Supergiant','Pune',inplace=True)
deliveries_2['bowling_team'].replace('Delhi Capitals','Delhi',inplace=True)
deliveries_2['bowling_team'].fillna("Unknown", inplace = True)

In [ ]:
deliveries_2['bowling_team'].unique()

array(['Bangalore', 'Kolkata', 'Chennai', 'Punjab', 'Delhi', 'Rajasthan',
       'Mumbai', 'Hyderabad', 'Kerala', 'Pune', 'Unknown', 'Gujarat'],
      dtype=object)

In [ ]:
deliveries_2.head()

       id  inning  over  ball  ... fielder extras_type batting_team  bowling_team
0  335982       1     6     5  ...     NaN         NaN      Kolkata     Bangalore
1  335982       1     6     6  ...     NaN         NaN      Kolkata     Bangalore
2  335982       1     7     1  ...     NaN         NaN      Kolkata     Bangalore
3  335982       1     7     2  ...     NaN         NaN      Kolkata     Bangalore
4  335982       1     7     3  ...     NaN         NaN      Kolkata     Bangalore

[5 rows x 18 columns]

In [ ]:
deliveries_2['inning'].isnull().unique()

array([False])

In [ ]:
deliveries_2['inning'].unique()

array([1, 2])

In [ ]:
deliveries_2['over'].isnull().unique()

array([False])

In [ ]:
deliveries_2['over'].unique()

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  0,  1,  2,
        3,  4,  5])

In [ ]:
deliveries_2['ball'].isnull().unique()

array([False])

In [ ]:
deliveries_2['ball'].unique()

array([5, 6, 1, 2, 3, 4, 7, 8, 9])

In [ ]:
deliveries_2['batsman'].isnull().unique()

array([False])

In [ ]:
deliveries_2['batsman'].unique()

array(['RT Ponting', 'BB McCullum', 'DJ Hussey', 'Mohammad Hafeez',
       'SC Ganguly', 'CL White', 'MV Boucher', 'B Akhil', 'AA Noffke',
       'P Kumar', 'Z Khan', 'SB Joshi', 'W Jaffer', 'JH Kallis',
       'R Dravid', 'V Kohli', 'K Goel', 'MEK Hussey', 'JR Hopes',
       'SK Raina', 'JDP Oram', 'S Badrinath', 'PA Patel', 'ML Hayden',
       'MS Dhoni', 'KC Sangakkara', 'Yuvraj Singh', 'SM Katich',
       'IK Pathan', 'T Kohli', 'YK Pathan', 'S Dhawan', 'G Gambhir',
       'SK Warne', 'D Salunkhe', 'SK Trivedi', 'V Sehwag', 'SR Watson',
       'M Kaif', 'DS Lehmann', 'RA Jadeja', 'M Rawat', 'L Ronchi',
       'ST Jayasuriya', 'DJ Thornely', 'RV Uthappa', 'PR Shah',
       'AM Nayar', 'SM Pollock', 'Harbhajan Singh', 'S Chanderpaul',
       'LRPL Taylor', 'WP Saha', 'AS Yadav', 'A Symonds', 'SB Bangar',
       'WPUJC Vaas', 'RP Singh', 'AC Gilchrist', 'Y Venugopal Rao',
       'VVS Laxman', 'RG Sharma', 'SB Styris', 'LR Shukla', 'PP Chawla',
       'Kamran Akmal', 'DPMD Jayawardene', 'S Sohal', 'B Lee', 'WA Mota',
       'Shahid Afridi', 'DJ Bravo', 'A Nehra', 'MA Khote', 'GC Smith',
       'Pankaj Singh', 'S Sreesanth', 'VRV Singh', 'SS Tiwary',
       'RR Sarwan', 'DS Kulkarni', 'R Vinay Kumar', 'M Kartik',
       'I Sharma', 'AB Agarkar', 'AM Rahane', 'TM Srivastava',
       'Shoaib Malik', 'MK Tiwary', 'KD Karthik', 'R Bhatia',
       'MF Maharoof', 'VY Mahesh', 'B Chipli', 'DW Steyn', 'DB Das',
       'MK Pandey', 'HH Gibbs', 'DNT Zoysa', 'D Kalyankrishna',
       'SE Marsh', 'SA Asnodkar', 'BJ Hodge', 'Sohail Tanvir',
       'Salman Butt', 'Umar Gul', 'AB Dinda', 'AB de Villiers',
       'SP Fleming', 'S Vidyut', 'JA Morkel', 'LPC Silva', 'DB Ravi Teja',
       'Misbah-ul-Haq', 'PJ Sangwan', 'YV Takawale', 'RR Raje',
       'Mohammad Asif', 'GD McGrath', 'Joginder Sharma', 'MS Gony',
       'M Muralitharan', 'M Ntini', 'DT Patil', 'A Kumble', 'S Anirudha',
       'MM Patel', 'CK Kapugedera', 'A Chopra', 'T Taibu', 'J Arunkumar',
       'PP Ojha', 'SP Goswami', 'SR Tendulkar', 'U Kaul', 'Niraj Patel',
       'AD Mascarenhas', 'TM Dilshan', 'A Mishra', 'LA Pomersbach',
       'Iqbal Abdulla', 'Younis Khan', 'PM Sarvesh Kumar',
       'DP Vijaykumar', 'Shoaib Akhtar', 'Abdur Razzak', 'H Das',
       'DR Smith', 'SD Chitnis', 'CRD Fernando', 'VS Yeligati',
       'L Balaji', 'A Mukund', 'RR Powar', 'JP Duminy', 'A Flintoff',
       'T Thushara', 'KP Pietersen', 'JD Ryder', 'T Henderson',
       'Kamran Khan', 'RS Bopara', 'MC Henriques', 'CH Gayle',
       'R Bishnoi', 'KV Sharma', 'FH Edwards', 'AS Raut', 'PC Valthaty',
       'RJ Quiney', 'Yashpal Singh', 'M Manhas', 'AA Bilakhia',
       'AN Ghosh', 'BAW Mendis', 'DL Vettori', 'MN van Wyk',
       'RE van der Merwe', 'TL Suman', 'Shoaib Ahmed', 'GR Napier',
       'KP Appanna', 'LA Carseldine', 'NV Ojha', 'SM Harwood', 'M Vijay',
       'DA Warner', 'SB Jakati', 'RJ Harris', 'D du Preez', 'M Morkel',
       'AD Mathews', 'SL Malinga', 'C Nanda', 'J Botha',
       'Mashrafe Mortaza', 'A Singh', 'GJ Bailey', 'AB McDonald',
       'Y Nagar', 'SS Shaikh', 'R Ashwin', 'Mohammad Ashraful',
       'Jaskaran Singh', 'Anirudh Singh', 'CA Pujara', 'OA Shah',
       'AP Tare', 'AT Rayudu', 'R Sathish', 'R McLaren',
       'AA Jhunjhunwala', 'P Dogra', 'A Uniyal', 'MS Bisla', 'YA Abdulla',
       'EJG Morgan', 'JM Kemp', 'S Tyagi', 'RS Gavaskar', 'SE Bond',
       'S Ladda', 'DP Nannes', 'KA Pollard', 'DR Martyn', 'S Narwal',
       'MJ Lumb', 'Bipul Sharma', 'AB Barath', 'FY Fazal', 'AC Voges',
       'MD Mishra', 'UT Yadav', 'J Theron', 'SJ Srivastava', 'R Sharma',
       'Mandeep Singh', 'KM Jadhav', 'SW Tait', 'KB Arun Karthik',
       'KAJ Roach', 'PD Collingwood', 'CK Langeveldt', 'VS Malik',
       'A Mithun', 'AP Dole', 'AN Ahmed', 'RS Sodhi', 'DE Bollinger',
       'S Sriram', 'B Sumanth', 'C Madan', 'AG Paunikar', 'MR Marsh',
       'AJ Finch', 'STR Binny', 'Harmeet Singh', 'IR Jaggi',
       'DT Christian', 'MA Agarwal', 'RV Gomez', 'AUK Pathan',
       'UBT Chand', 'DJ Jacobs', 'NJ Rimmington', 'Sunny Singh',
       'AL Menaria', 'WD Parnell', 'JJ van der Wath', 'R Ninan',
       'S Aravind', 'MS Wade', 'TD Paine', 'JEC Franklin', 'SB Wagh',
       'AC Thomas', 'Shakib Al Hasan', 'DH Yagnik', 'S Randiv',
       'BJ Haddin', 'NLTC Perera', 'NL McCullum', 'JE Taylor',
       'J Syed Mohammad', 'RN ten Doeschate', 'TR Birt', 'AG Murtaza',
       'Harpreet Singh', 'M Klinger', 'AC Blizzard', 'I Malhotra',
       'L Ablish', 'CA Ingram', 'S Nadeem', 'P Parameswaran',
       'CJ Ferguson', 'VR Aaron', 'AA Chavan', 'ND Doshi', 'B Kumar',
       'Y Gnaneswara Rao', 'S Rana', 'BA Bhatt', 'F du Plessis',
       'RE Levi', 'GJ Maxwell', 'SPD Smith', 'SA Yadav', 'MN Samuels',
       'KK Cooper', 'JP Faulkner', 'HV Patel', 'DAJ Bracewell',
       'DJ Harris', 'Ankit Sharma', 'SP Narine', 'GB Hogg', 'RR Bhatkal',
       'CJ McKay', 'N Saini', 'DA Miller', 'Azhar Mahmood', 'P Negi',
       'RJ Peterson', 'KMDN Kulasekara', 'A Ashish Reddy',
       'V Pratap Singh', 'BB Samantray', 'MJ Clarke', 'Gurkeerat Singh',
       'AP Majumdar', 'PA Reddy', 'K Upadhyay', 'P Awana', 'AD Russell',
       'A Chandila', 'CA Lynn', 'Sunny Gupta', 'MC Juneja', 'KK Nair',
       'GH Vihari', 'R Shukla', 'MDKJ Perera', 'AS Rajpoot', 'B Laughlin',
       'M Vohra', 'JD Unadkat', 'Mohammed Shami', 'BMAJ Mendis',
       'R Rampaul', 'CH Morris', 'SV Samson', 'SMSM Senanayake',
       'BJ Rohrer', 'KL Rahul', 'Q de Kock', 'R Dhawan', 'MG Johnson',
       'LJ Wright', 'IC Pandey', 'CM Gautam', 'X Thalaivan Sargunam',
       'DJG Sammy', 'KW Richardson', 'MM Sharma', 'UA Birla',
       'Parvez Rasool', 'Sandeep Sharma', 'S Kaul', 'Sachin Baby',
       'PV Tambe', 'NM Coulter-Nile', 'CJ Anderson', 'NJ Maddinson',
       'AR Patel', 'JJ Bumrah', 'JDS Neesham', 'TG Southee', 'MA Starc',
       'BR Dunk', 'RR Rossouw', 'Shivam Sharma', 'YS Chahal',
       'LMP Simmons', 'VH Zol', 'Imran Tahir', 'BCJ Cutting',
       'BE Hendricks', 'S Gopal', 'M de Lange', 'R Tewatia', 'JO Holder',
       'Karanveer Singh', 'SS Iyer', 'DJ Hooda', 'Anureet Singh',
       'KS Williamson', 'SA Abbott', 'J Suchith', 'RG More', 'D Wiese',
       'HH Pandya', 'SN Khan', 'MJ McClenaghan', 'DJ Muthuswami',
       'PJ Cummins', 'SN Thakur', 'JC Buttler', 'CR Brathwaite',
       'MP Stoinis', 'Ishan Kishan', 'C Munro', 'P Sahu', 'KH Pandya',
       'AD Nath', 'MJ Guptill', 'KJ Abbott', 'TM Head', 'M Ashwin',
       'NS Naik', 'RR Pant', 'SW Billings', 'KC Cariappa',
       'PSP Handscomb', 'Swapnil Singh', 'J Yadav', 'UT Khawaja',
       'HM Amla', 'F Behardien', 'A Zampa', 'BB Sran', 'N Rana',
       'S Kaushik', 'ER Dwivedi', 'CJ Jordan', 'A Choudhary', 'TS Mills',
       'BA Stokes', 'JJ Roy', 'Vishnu Vinod', 'Basil Thampi', 'CR Woakes',
       'RA Tripathi', 'DL Chahar', 'V Shankar', 'Rashid Khan',
       'LH Ferguson', 'RD Chahar', 'C de Grandhomme', 'AF Milne',
       'S Badree', 'Mohammad Nabi', 'AJ Tye', 'K Rabada', 'Kuldeep Yadav',
       'Washington Sundar', 'DM Bravo', 'AR Bawne', 'SP Jackson',
       'Ankit Soni', 'TA Boult', 'E Lewis', 'MA Wood', 'RK Singh',
       'DJM Short', 'K Gowtham', 'TK Curran', 'M Markande', 'B Stanlake',
       'Mujeeb Ur Rahman', 'A Dananjaya', 'Shivam Mavi', 'Shubman Gill',
       'Mohammed Siraj', 'H Klaasen', 'RK Bhui', 'JC Archer', 'PP Shaw',
       'LE Plunkett', 'Mustafizur Rahman', 'AD Hales', 'MK Lomror',
       'DR Shorey', 'MM Ali', 'M Prasidh Krishna', 'P Chopra',
       'JPR Scantlebury-Searles', 'Abhishek Sharma', 'IS Sodhi',
       'SO Hetmyer', 'S Dube', 'NA Saini', 'JM Bairstow', 'Rasikh Salam',
       'KMA Paul', 'N Pooran', 'P Ray Barman', 'S Lamichhane',
       'SM Curran', 'GC Viljoen', 'Avesh Khan', 'HF Gurney', 'SD Lad',
       'AS Joseph', 'MJ Santner', 'R Parag', 'JL Denly', 'LS Livingstone',
       'KK Ahmed', 'AJ Turner', 'SE Rutherford', 'Harpreet Brar',
       'Y Prithvi Raj', 'P Simran Singh', 'JL Pattinson', 'A Nortje',
       'T Banton', 'D Padikkal', 'YBK Jaiswal', 'RD Gaikwad',
       'TU Deshpande', 'Abdul Samad', 'PK Garg', 'JR Philippe',
       'Kartik Tyagi', 'CV Varun', 'KL Nagarkoti', 'I Udana',
       'Ravi Bishnoi', 'Shahbaz Ahmed', 'AT Carey', 'N Jagadeesan',
       'T Natarajan', 'P Dubey', 'SS Cottrell', 'Arshdeep Singh',
       'DR Sams'], dtype=object)

In [ ]:
deliveries_2['non_striker'].isnull().unique()

array([False])

In [ ]:
deliveries_2['non_striker'].unique()

array(['BB McCullum', 'RT Ponting', 'DJ Hussey', 'Mohammad Hafeez',
       'SC Ganguly', 'MV Boucher', 'CL White', 'B Akhil', 'AA Noffke',
       'P Kumar', 'Z Khan', 'SB Joshi', 'JH Kallis', 'W Jaffer',
       'R Dravid', 'V Kohli', 'JR Hopes', 'S Badrinath', 'K Goel',
       'SK Raina', 'MEK Hussey', 'JDP Oram', 'ML Hayden', 'PA Patel',
       'MS Dhoni', 'KC Sangakkara', 'Yuvraj Singh', 'SM Katich',
       'IK Pathan', 'YK Pathan', 'T Kohli', 'G Gambhir', 'S Dhawan',
       'D Salunkhe', 'SK Warne', 'SK Trivedi', 'V Sehwag', 'SR Watson',
       'M Kaif', 'DS Lehmann', 'RA Jadeja', 'M Rawat', 'ST Jayasuriya',
       'L Ronchi', 'DJ Thornely', 'RV Uthappa', 'PR Shah', 'AM Nayar',
       'SM Pollock', 'Harbhajan Singh', 'S Chanderpaul', 'LRPL Taylor',
       'WP Saha', 'A Symonds', 'AS Yadav', 'SB Bangar', 'WPUJC Vaas',
       'RP Singh', 'PP Ojha', 'Y Venugopal Rao', 'AC Gilchrist',
       'VVS Laxman', 'SB Styris', 'LR Shukla', 'WA Mota', 'Kamran Akmal',
       'DPMD Jayawardene', 'S Sohal', 'PP Chawla', 'RG Sharma',
       'Shahid Afridi', 'DJ Bravo', 'A Nehra', 'MA Khote', 'Pankaj Singh',
       'GC Smith', 'B Lee', 'S Sreesanth', 'VRV Singh', 'SS Tiwary',
       'RR Sarwan', 'DS Kulkarni', 'R Vinay Kumar', 'M Kartik',
       'I Sharma', 'AB Dinda', 'AB Agarkar', 'AM Rahane', 'TM Srivastava',
       'Shoaib Malik', 'MK Tiwary', 'KD Karthik', 'R Bhatia',
       'MF Maharoof', 'VY Mahesh', 'B Chipli', 'DW Steyn', 'DB Das',
       'MK Pandey', 'HH Gibbs', 'DNT Zoysa', 'D Kalyankrishna',
       'SE Marsh', 'SA Asnodkar', 'BJ Hodge', 'Sohail Tanvir',
       'Salman Butt', 'Umar Gul', 'AB de Villiers', 'SP Fleming',
       'S Vidyut', 'JA Morkel', 'Joginder Sharma', 'DB Ravi Teja',
       'LPC Silva', 'Misbah-ul-Haq', 'DP Vijaykumar', 'PJ Sangwan',
       'YV Takawale', 'RR Raje', 'Mohammad Asif', 'GD McGrath', 'MS Gony',
       'M Ntini', 'DT Patil', 'A Kumble', 'S Anirudha', 'MM Patel',
       'CK Kapugedera', 'A Chopra', 'T Taibu', 'J Arunkumar',
       'SP Goswami', 'SR Tendulkar', 'Niraj Patel', 'AD Mascarenhas',
       'TM Dilshan', 'A Mishra', 'LA Pomersbach', 'Iqbal Abdulla',
       'Younis Khan', 'PM Sarvesh Kumar', 'Shoaib Akhtar', 'Abdur Razzak',
       'H Das', 'DR Smith', 'SD Chitnis', 'CRD Fernando', 'A Nel',
       'RR Powar', 'JP Duminy', 'A Flintoff', 'KP Pietersen',
       'T Henderson', 'Kamran Khan', 'RS Bopara', 'MC Henriques',
       'CH Gayle', 'R Bishnoi', 'KV Sharma', 'FH Edwards', 'DL Vettori',
       'L Balaji', 'M Muralitharan', 'AS Raut', 'PC Valthaty',
       'Yashpal Singh', 'JD Ryder', 'M Manhas', 'RJ Quiney',
       'AA Bilakhia', 'AN Ghosh', 'BAW Mendis', 'MN van Wyk',
       'RE van der Merwe', 'TL Suman', 'GR Napier', 'KP Appanna',
       'LA Carseldine', 'NV Ojha', 'SM Harwood', 'M Vijay', 'DA Warner',
       'SB Jakati', 'S Tyagi', 'RJ Harris', 'Shoaib Ahmed', 'D du Preez',
       'SL Malinga', 'M Morkel', 'AD Mathews', 'J Botha',
       'Mashrafe Mortaza', 'Jaskaran Singh', 'GJ Bailey', 'AB McDonald',
       'Y Nagar', 'A Singh', 'SS Shaikh', 'R Ashwin', 'T Thushara',
       'Mohammad Ashraful', 'Anirudh Singh', 'CA Pujara', 'OA Shah',
       'AP Tare', 'AT Rayudu', 'R Sathish', 'AA Jhunjhunwala', 'P Dogra',
       'R McLaren', 'MS Bisla', 'YA Abdulla', 'EJG Morgan', 'JM Kemp',
       'A Uniyal', 'RS Gavaskar', 'SE Bond', 'S Ladda', 'DP Nannes',
       'KA Pollard', 'DR Martyn', 'MJ Lumb', 'Bipul Sharma', 'AB Barath',
       'FY Fazal', 'AC Voges', 'MD Mishra', 'UT Yadav', 'J Theron',
       'SJ Srivastava', 'Mandeep Singh', 'KM Jadhav', 'S Narwal',
       'SW Tait', 'KB Arun Karthik', 'KAJ Roach', 'PD Collingwood',
       'VS Malik', 'C Ganapathy', 'R Sharma', 'A Mithun', 'AP Dole',
       'Harmeet Singh', 'AN Ahmed', 'RS Sodhi', 'S Sriram', 'B Sumanth',
       'C Madan', 'AG Paunikar', 'DE Bollinger', 'MR Marsh', 'AJ Finch',
       'STR Binny', 'IR Jaggi', 'DT Christian', 'MA Agarwal', 'RV Gomez',
       'AUK Pathan', 'DJ Jacobs', 'NJ Rimmington', 'Sunny Singh',
       'UBT Chand', 'AL Menaria', 'WD Parnell', 'R Ninan', 'S Aravind',
       'JJ van der Wath', 'S Nadeem', 'MS Wade', 'TD Paine', 'AC Thomas',
       'JEC Franklin', 'SB Wagh', 'Shakib Al Hasan', 'DH Yagnik',
       'S Randiv', 'BJ Haddin', 'NLTC Perera', 'NL McCullum', 'JE Taylor',
       'J Syed Mohammad', 'RN ten Doeschate', 'TR Birt', 'AG Murtaza',
       'Harpreet Singh', 'M Klinger', 'AC Blizzard', 'I Malhotra',
       'L Ablish', 'P Parameswaran', 'CJ Ferguson', 'CA Ingram',
       'VR Aaron', 'AA Chavan', 'ND Doshi', 'B Kumar', 'CK Langeveldt',
       'Y Gnaneswara Rao', 'S Rana', 'BA Bhatt', 'F du Plessis',
       'RE Levi', 'GJ Maxwell', 'SPD Smith', 'SA Yadav', 'MN Samuels',
       'JP Faulkner', 'DAJ Bracewell', 'DJ Harris', 'Ankit Sharma',
       'TP Sudhindra', 'KK Cooper', 'HV Patel', 'GB Hogg', 'RR Bhatkal',
       'CJ McKay', 'N Saini', 'DA Miller', 'Azhar Mahmood', 'P Negi',
       'RJ Peterson', 'P Awana', 'KMDN Kulasekara', 'A Ashish Reddy',
       'BB Samantray', 'MJ Clarke', 'Gurkeerat Singh', 'AP Majumdar',
       'PA Reddy', 'K Upadhyay', 'SP Narine', 'AD Russell', 'CA Lynn',
       'Sunny Gupta', 'MC Juneja', 'KK Nair', 'GH Vihari', 'MDKJ Perera',
       'AS Rajpoot', 'B Laughlin', 'M Vohra', 'JD Unadkat',
       'Mohammed Shami', 'BMAJ Mendis', 'R Rampaul', 'CH Morris',
       'SV Samson', 'SMSM Senanayake', 'BJ Rohrer', 'KL Rahul',
       'Q de Kock', 'R Dhawan', 'MG Johnson', 'A Chandila', 'LJ Wright',
       'CM Gautam', 'X Thalaivan Sargunam', 'DJG Sammy', 'A Mukund',
       'KW Richardson', 'UA Birla', 'Parvez Rasool', 'Sandeep Sharma',
       'S Kaul', 'Sachin Baby', 'PV Tambe', 'NM Coulter-Nile',
       'MM Sharma', 'CJ Anderson', 'NJ Maddinson', 'AR Patel',
       'JJ Bumrah', 'JDS Neesham', 'BW Hilfenhaus', 'TG Southee',
       'MA Starc', 'YS Chahal', 'BR Dunk', 'RR Rossouw', 'R Shukla',
       'LMP Simmons', 'VH Zol', 'Imran Tahir', 'BCJ Cutting',
       'BE Hendricks', 'S Gopal', 'M de Lange', 'R Tewatia', 'JO Holder',
       'Karanveer Singh', 'DJ Muthuswami', 'SS Iyer', 'DJ Hooda',
       'Anureet Singh', 'KS Williamson', 'SA Abbott', 'J Suchith',
       'RG More', 'D Wiese', 'HH Pandya', 'SN Khan', 'MJ McClenaghan',
       'SN Thakur', 'JC Buttler', 'CR Brathwaite', 'MP Stoinis',
       'Ishan Kishan', 'C Munro', 'P Sahu', 'KH Pandya', 'AD Nath',
       'KJ Abbott', 'TM Head', 'NS Naik', 'RR Pant', 'SW Billings',
       'KC Cariappa', 'S Kaushik', 'PSP Handscomb', 'Swapnil Singh',
       'J Yadav', 'UT Khawaja', 'HM Amla', 'F Behardien', 'BB Sran',
       'N Rana', 'MJ Guptill', 'ER Dwivedi', 'CJ Jordan', 'TS Mills',
       'A Choudhary', 'BA Stokes', 'JJ Roy', 'Vishnu Vinod', 'PJ Cummins',
       'Basil Thampi', 'CR Woakes', 'A Zampa', 'RA Tripathi', 'DL Chahar',
       'Rashid Khan', 'V Shankar', 'RD Chahar', 'LH Ferguson',
       'C de Grandhomme', 'AF Milne', 'S Badree', 'Mohammad Nabi',
       'AJ Tye', 'K Rabada', 'Kuldeep Yadav', 'DM Bravo', 'AR Bawne',
       'SP Jackson', 'Ankit Soni', 'Washington Sundar', 'TA Boult',
       'E Lewis', 'MA Wood', 'RK Singh', 'DJM Short', 'K Gowtham',
       'TK Curran', 'M Markande', 'B Stanlake', 'Mujeeb Ur Rahman',
       'A Dananjaya', 'Shubman Gill', 'Shivam Mavi', 'Mohammed Siraj',
       'H Klaasen', 'JC Archer', 'PP Shaw', 'LE Plunkett',
       'Mustafizur Rahman', 'AD Hales', 'MK Lomror', 'DR Shorey',
       'MM Ali', 'M Prasidh Krishna', 'P Chopra',
       'JPR Scantlebury-Searles', 'Abhishek Sharma', 'IS Sodhi',
       'SO Hetmyer', 'S Dube', 'NA Saini', 'JM Bairstow', 'Rasikh Salam',
       'KMA Paul', 'N Pooran', 'P Ray Barman', 'Avesh Khan', 'SM Curran',
       'GC Viljoen', 'AS Joseph', 'HF Gurney', 'SD Lad', 'R Parag',
       'LS Livingstone', 'RK Bhui', 'AJ Turner', 'SE Rutherford',
       'Harpreet Brar', 'Y Prithvi Raj', 'M Ashwin', 'MJ Santner',
       'P Simran Singh', 'JL Pattinson', 'T Banton', 'D Padikkal',
       'YBK Jaiswal', 'TU Deshpande', 'A Nortje', 'Abdul Samad',
       'PK Garg', 'T Natarajan', 'Ravi Bishnoi', 'JR Philippe',
       'Kartik Tyagi', 'I Udana', 'KL Nagarkoti', 'Shahbaz Ahmed',
       'RD Gaikwad', 'AT Carey', 'CV Varun', 'N Jagadeesan', 'P Dubey',
       'SS Cottrell'], dtype=object)

In [ ]:
deliveries_2['bowler'].isnull().unique()

array([False])

In [ ]:
deliveries_2['bowler'].unique()

array(['AA Noffke', 'Z Khan', 'JH Kallis', 'SB Joshi', 'CL White',
       'P Kumar', 'AB Agarkar', 'SC Ganguly', 'LR Shukla', 'I Sharma',
       'AB Dinda', 'JDP Oram', 'JR Hopes', 'MS Gony', 'K Goel',
       'PP Chawla', 'WA Mota', 'IK Pathan', 'S Sreesanth', 'B Lee',
       'M Muralitharan', 'P Amarnath', 'Joginder Sharma', 'GD McGrath',
       'B Geeves', 'SK Warne', 'YK Pathan', 'D Salunkhe', 'SR Watson',
       'SK Trivedi', 'DL Vettori', 'MF Maharoof', 'MM Patel', 'R Bhatia',
       'B Akhil', 'R Vinay Kumar', 'A Nehra', 'SM Pollock', 'DS Kulkarni',
       'AM Nayar', 'Harbhajan Singh', 'ST Jayasuriya', 'WPUJC Vaas',
       'RP Singh', 'SB Styris', 'SB Bangar', 'DJ Hussey',
       'Mohammad Hafeez', 'M Kartik', 'PP Ojha', 'A Symonds',
       'Pankaj Singh', 'Mohammad Asif', 'VY Mahesh', 'Shahid Afridi',
       'MA Khote', 'DJ Bravo', 'VS Yeligati', 'D Kalyankrishna',
       'VRV Singh', 'A Kumble', 'Sohail Tanvir', 'DNT Zoysa',
       'SD Chitnis', 'Shoaib Malik', 'Yuvraj Singh', 'DW Steyn',
       'JA Morkel', 'CRD Fernando', 'V Sehwag', 'V Kohli',
       'Gagandeep Singh', 'Y Venugopal Rao', 'Umar Gul', 'M Ntini',
       'PJ Sangwan', 'DP Vijaykumar', 'DB Ravi Teja', 'LPC Silva',
       'DJ Thornely', 'RR Raje', 'SK Raina', 'S Vidyut', 'L Balaji',
       'CK Kapugedera', 'DR Smith', 'AD Mascarenhas', 'A Mishra',
       'Shoaib Akhtar', 'Iqbal Abdulla', 'RR Powar', 'PM Sarvesh Kumar',
       'Abdur Razzak', 'RA Jadeja', 'TM Dilshan', 'RG Sharma', 'A Nel',
       'BAW Mendis', 'A Flintoff', 'T Thushara', 'SL Malinga',
       'T Henderson', 'Kamran Khan', 'JD Ryder', 'DP Nannes', 'AM Salvi',
       'YA Abdulla', 'VS Malik', 'Harmeet Singh', 'FH Edwards',
       'MC Henriques', 'CH Gayle', 'KP Pietersen', 'LRPL Taylor',
       'RS Bopara', 'MK Tiwary', 'Anureet Singh', 'RR Bose', 'KP Appanna',
       'Shoaib Ahmed', 'BJ Hodge', 'SR Tendulkar', 'RE van der Merwe',
       'JP Duminy', 'S Tyagi', 'GR Napier', 'SM Harwood', 'AS Raut',
       'SB Jakati', 'D du Preez', 'TL Suman', 'RJ Harris', 'A Singh',
       'M Morkel', 'LA Carseldine', 'A Mithun', 'C Nanda', 'SS Sarkar',
       'AD Mathews', 'AM Rahane', 'J Botha', 'Mashrafe Mortaza',
       'AB McDonald', 'Y Nagar', 'CK Langeveldt', 'R Ashwin', 'RA Shaikh',
       'Jaskaran Singh', 'AA Jhunjhunwala', 'A Uniyal', 'SW Tait',
       'AG Murtaza', 'R Sathish', 'R McLaren', 'RS Gavaskar', 'JM Kemp',
       'S Ladda', 'Bipul Sharma', 'SE Bond', 'KA Pollard', 'S Narwal',
       'UT Yadav', 'SJ Srivastava', 'AC Voges', 'R Sharma', 'J Theron',
       'NLTC Perera', 'KAJ Roach', 'PD Collingwood', 'C Ganapathy',
       'MB Parmar', 'DE Bollinger', 'SB Wagh', 'JD Unadkat', 'AP Dole',
       'AN Ahmed', 'FY Fazal', 'MR Marsh', 'L Ablish', 'S Sriram',
       'AJ Finch', 'STR Binny', 'ND Doshi', 'S Randiv', 'TG Southee',
       'AL Menaria', 'DT Christian', 'AUK Pathan', 'RV Gomez',
       'JEC Franklin', 'WD Parnell', 'M Manhas', 'AC Thomas',
       'NJ Rimmington', 'RN ten Doeschate', 'S Nadeem', 'BA Bhatt',
       'R Ninan', 'JJ van der Wath', 'S Aravind', 'Shakib Al Hasan',
       'PC Valthaty', 'S Dhawan', 'J Syed Mohammad', 'VR Aaron',
       'JE Taylor', 'NL McCullum', 'KMDN Kulasekara', 'P Parameswaran',
       'I Malhotra', 'B Chipli', 'B Kumar', 'AA Kazi', 'Anand Rajan',
       'AA Chavan', 'P Prasanth', 'Y Gnaneswara Rao', 'S Rana',
       'JP Faulkner', 'SS Mundhe', 'RW Price', 'GJ Maxwell', 'M de Lange',
       'MN Samuels', 'KK Cooper', 'DAJ Bracewell', 'HV Patel',
       'Ankit Sharma', 'DJ Harris', 'TP Sudhindra', 'F du Plessis',
       'SP Narine', 'GB Hogg', 'RR Bhatkal', 'P Awana', 'V Pratap Singh',
       'CJ McKay', 'A Ashish Reddy', 'AD Russell', 'Azhar Mahmood',
       'A Chandila', 'P Negi', 'LJ Wright', 'RJ Peterson', 'R Shukla',
       'MJ Clarke', 'BW Hilfenhaus', 'SPD Smith', 'K Upadhyay',
       'Sunny Gupta', 'MG Johnson', 'JJ Bumrah', 'S Badree', 'AS Rajpoot',
       'B Laughlin', 'GH Vihari', 'Mohammed Shami', 'BMAJ Mendis',
       'CH Morris', 'Harmeet Singh (2)', 'S Kaul', 'R Dhawan',
       'MM Sharma', 'R Rampaul', 'SMSM Senanayake', 'KV Sharma',
       'JO Holder', 'IC Pandey', 'Sandeep Sharma', 'YS Chahal',
       'DJG Sammy', 'KW Richardson', 'P Suyal', 'PV Tambe', 'BJ Rohrer',
       'Parvez Rasool', 'MG Neser', 'NM Coulter-Nile', 'AC Gilchrist',
       'CJ Anderson', 'MA Starc', 'JDS Neesham', 'AR Patel', 'M Vijay',
       'R Tewatia', 'SA Yadav', 'Shivam Sharma', 'Imran Tahir',
       'V Shankar', 'LMP Simmons', 'BCJ Cutting', 'S Gopal', 'K Santokie',
       'BE Hendricks', 'PJ Cummins', 'JW Hastings', 'Karanveer Singh',
       'DJ Muthuswami', 'TA Boult', 'SA Abbott', 'KC Cariappa',
       'DJ Hooda', 'J Suchith', 'RG More', 'MJ McClenaghan', 'D Wiese',
       'HH Pandya', 'SN Thakur', 'GS Sandhu', 'Gurkeerat Singh',
       'J Yadav', 'BB Sran', 'M Ashwin', 'CR Brathwaite', 'C Munro',
       'MP Stoinis', 'P Sahu', 'Mustafizur Rahman', 'AF Milne',
       'Kuldeep Yadav', 'KH Pandya', 'KJ Abbott', 'T Shamsi', 'S Kaushik',
       'SM Boland', 'Swapnil Singh', 'CJ Jordan', 'A Zampa',
       'Sachin Baby', 'N Rana', 'DL Chahar', 'KS Williamson', 'TM Head',
       'A Choudhary', 'TS Mills', 'Rashid Khan', 'BA Stokes', 'CR Woakes',
       'T Natarajan', 'RD Chahar', 'B Stanlake', 'Basil Thampi',
       'Tejas Baroka', 'C de Grandhomme', 'AJ Tye', 'LH Ferguson',
       'Mohammad Nabi', 'Mohammed Siraj', 'K Rabada', 'Washington Sundar',
       'SS Agarwal', 'NB Singh', 'RA Tripathi', 'Ankit Soni', 'MJ Henry',
       'Avesh Khan', 'MA Wood', 'M Markande', 'Mujeeb Ur Rahman',
       'K Khejroliya', 'K Gowtham', 'DJM Short', 'TK Curran',
       'A Dananjaya', 'Shivam Mavi', 'JC Archer', 'LE Plunkett',
       'IS Sodhi', 'MK Lomror', 'KM Asif', 'L Ngidi', 'DJ Willey',
       'M Prasidh Krishna', 'MM Ali', 'JPR Scantlebury-Searles',
       'S Lamichhane', 'CJ Dala', 'KK Ahmed', 'NA Saini', 'S Dube',
       'Rasikh Salam', 'KMA Paul', 'SM Curran', 'CV Varun', 'GC Viljoen',
       'Mandeep Singh', 'P Ray Barman', 'MJ Santner', 'JP Behrendorff',
       'SC Kuggeleijn', 'AS Joseph', 'HF Gurney', 'S Midhun', 'R Parag',
       'LS Livingstone', 'SN Khan', 'Abhishek Sharma', 'Arshdeep Singh',
       'Harpreet Brar', 'SE Rutherford', 'Y Prithvi Raj', 'O Thomas',
       'AS Roy', 'S Sandeep Warrier', 'JL Pattinson', 'SS Cottrell',
       'A Nortje', 'Ravi Bishnoi', 'I Udana', 'TU Deshpande',
       'KL Nagarkoti', 'Kartik Tyagi', 'DR Sams', 'Shahbaz Ahmed',
       'Abdul Samad', 'JR Hazlewood', 'DA Warner', 'CJ Green', 'P Dubey',
       'Monu Kumar'], dtype=object)

In [ ]:
deliveries_2['batsman_runs'].isnull().unique()

array([False])

In [ ]:
deliveries_2['batsman_runs'].unique()

array([1, 0, 2, 6, 4, 5, 3])

In [ ]:
deliveries_2.columns

Index(['id', 'inning', 'over', 'ball', 'batsman', 'non_striker', 'bowler',
       'batsman_runs', 'extra_runs', 'total_runs', 'non_boundary', 'is_wicket',
       'dismissal_kind', 'player_dismissed', 'fielder', 'extras_type',
       'batting_team', 'bowling_team'],
      dtype='object')

In [ ]:
deliveries_2['extra_runs'].isnull().unique()

array([False])

In [ ]:
deliveries_2['extra_runs'].unique()

array([0, 4, 1, 2, 5, 3, 7])

In [ ]:
deliveries_2['total_runs'].isnull().unique()

array([False])

In [ ]:
deliveries_2['total_runs'].unique()

array([1, 0, 2, 6, 4, 5, 3, 7])

In [ ]:
deliveries_2['non_boundary'].isnull().unique()

array([False])

In [ ]:
deliveries_2['non_boundary'].unique()

array([0, 1])

In [ ]:
deliveries_2.columns

Index(['id', 'inning', 'over', 'ball', 'batsman', 'non_striker', 'bowler',
       'batsman_runs', 'extra_runs', 'total_runs', 'non_boundary', 'is_wicket',
       'dismissal_kind', 'player_dismissed', 'fielder', 'extras_type',
       'batting_team', 'bowling_team'],
      dtype='object')

In [ ]:
deliveries_2['is_wicket'].isnull().unique()

array([False])

In [ ]:
deliveries_2['is_wicket'].unique()

array([0, 1])

In [ ]:
deliveries_2['dismissal_kind'].isnull().unique()

array([ True, False])

In [ ]:
deliveries_2['dismissal_kind'].unique()

array([nan, 'caught', 'run out', 'bowled', 'lbw', 'retired hurt',
       'stumped', 'caught and bowled', 'hit wicket',
       'obstructing the field'], dtype=object)

In [ ]:
deliveries_2['dismissal_kind'].fillna("none", inplace = True)

In [ ]:
deliveries_2['dismissal_kind'].unique()

array(['none', 'caught', 'run out', 'bowled', 'lbw', 'retired hurt',
       'stumped', 'caught and bowled', 'hit wicket',
       'obstructing the field'], dtype=object)

In [ ]:
deliveries_2.columns

Index(['id', 'inning', 'over', 'ball', 'batsman', 'non_striker', 'bowler',
       'batsman_runs', 'extra_runs', 'total_runs', 'non_boundary', 'is_wicket',
       'dismissal_kind', 'player_dismissed', 'fielder', 'extras_type',
       'batting_team', 'bowling_team'],
      dtype='object')

In [ ]:
deliveries_2['player_dismissed'].unique()

array([nan, 'RT Ponting', 'DJ Hussey', 'SC Ganguly', 'MV Boucher',
       'B Akhil', 'CL White', 'AA Noffke', 'Z Khan', 'SB Joshi',
       'JH Kallis', 'W Jaffer', 'R Dravid', 'V Kohli', 'SK Raina',
       'JDP Oram', 'PA Patel', 'ML Hayden', 'MS Dhoni', 'JR Hopes',
       'Yuvraj Singh', 'KC Sangakkara', 'K Goel', 'SK Warne', 'V Sehwag',
       'T Kohli', 'YK Pathan', 'SR Watson', 'DS Lehmann', 'M Kaif',
       'M Rawat', 'RA Jadeja', 'DJ Thornely', 'L Ronchi', 'ST Jayasuriya',
       'PR Shah', 'RV Uthappa', 'AM Nayar', 'SM Pollock', 'S Chanderpaul',
       'LRPL Taylor', 'BB McCullum', 'WP Saha', 'AS Yadav', 'A Symonds',
       'WPUJC Vaas', 'SB Bangar', 'PP Ojha', 'Y Venugopal Rao',
       'VVS Laxman', 'AC Gilchrist', 'RG Sharma', 'SB Styris',
       'Mohammad Hafeez', 'Kamran Akmal', 'DPMD Jayawardene', 'IK Pathan',
       'B Lee', 'S Sohal', 'G Gambhir', 'Shahid Afridi', 'MEK Hussey',
       'Harbhajan Singh', 'DJ Bravo', 'MA Khote', 'GC Smith',
       'D Salunkhe', 'PP Chawla', 'S Sreesanth', 'VRV Singh', 'RR Sarwan',
       'SS Tiwary', 'P Kumar', 'M Kartik', 'LR Shukla', 'AB Agarkar',
       'AM Rahane', 'SM Katich', 'TM Srivastava', 'S Dhawan',
       'Shoaib Malik', 'KD Karthik', 'R Bhatia', 'MK Tiwary',
       'MF Maharoof', 'B Chipli', 'DW Steyn', 'DB Das', 'MK Pandey',
       'HH Gibbs', 'DNT Zoysa', 'D Kalyankrishna', 'SA Asnodkar',
       'BJ Hodge', 'Salman Butt', 'Umar Gul', 'AB Dinda', 'SP Fleming',
       'S Vidyut', 'JA Morkel', 'LPC Silva', 'Misbah-ul-Haq',
       'DB Ravi Teja', 'RP Singh', 'SE Marsh', 'AB de Villiers',
       'YV Takawale', 'Mohammad Asif', 'GD McGrath', 'PJ Sangwan',
       'S Badrinath', 'Joginder Sharma', 'M Muralitharan', 'M Ntini',
       'DT Patil', 'A Kumble', 'S Anirudha', 'Sohail Tanvir',
       'SK Trivedi', 'CK Kapugedera', 'A Chopra', 'J Arunkumar',
       'T Taibu', 'R Vinay Kumar', 'SP Goswami', 'AD Mascarenhas',
       'A Mishra', 'VY Mahesh', 'TM Dilshan', 'SR Tendulkar',
       'Younis Khan', 'Niraj Patel', 'Shoaib Akhtar', 'I Sharma', 'H Das',
       'DR Smith', 'SD Chitnis', 'A Nehra', 'VS Yeligati', 'MS Gony',
       'L Balaji', 'LA Pomersbach', 'A Nel', 'A Mukund', 'WA Mota',
       'JP Duminy', 'A Flintoff', 'KP Pietersen', 'JD Ryder',
       'T Henderson', 'MM Patel', 'Kamran Khan', 'RS Bopara',
       'MC Henriques', 'CH Gayle', 'R Bishnoi', 'KV Sharma',
       'PC Valthaty', 'RJ Quiney', 'Yashpal Singh', 'Pankaj Singh',
       'FH Edwards', 'AS Raut', 'AN Ghosh', 'BAW Mendis', 'DL Vettori',
       'RE van der Merwe', 'RR Powar', 'AA Bilakhia', 'TL Suman',
       'Shoaib Ahmed', 'GR Napier', 'MN van Wyk', 'LA Carseldine',
       'NV Ojha', 'M Vijay', 'DA Warner', 'SB Jakati', 'M Manhas',
       'RJ Harris', 'D du Preez', 'RR Raje', 'DS Kulkarni', 'M Morkel',
       'AD Mathews', 'S Tyagi', 'SL Malinga', 'C Nanda', 'J Botha',
       'A Singh', 'GJ Bailey', 'AB McDonald', 'Y Nagar', 'SS Shaikh',
       'R Ashwin', 'T Thushara', 'Mohammad Ashraful', 'Anirudh Singh',
       'CA Pujara', 'AP Tare', 'AT Rayudu', 'R Sathish',
       'AA Jhunjhunwala', 'P Dogra', 'A Uniyal', 'MS Bisla', 'EJG Morgan',
       'JM Kemp', 'OA Shah', 'RS Gavaskar', 'SE Bond', 'KA Pollard',
       'DP Nannes', 'DR Martyn', 'S Narwal', 'MJ Lumb', 'AB Barath',
       'FY Fazal', 'MD Mishra', 'S Ladda', 'J Theron', 'SJ Srivastava',
       'R Sharma', 'Mandeep Singh', 'AC Voges', 'Jaskaran Singh',
       'KAJ Roach', 'PD Collingwood', 'CK Langeveldt', 'VS Malik',
       'KM Jadhav', 'SW Tait', 'A Mithun', 'AP Dole', 'Harmeet Singh',
       'R McLaren', 'S Sriram', 'KP Appanna', 'C Madan', 'AG Paunikar',
       'MR Marsh', 'AJ Finch', 'STR Binny', 'B Sumanth', 'IR Jaggi',
       'DT Christian', 'MA Agarwal', 'RV Gomez', 'UT Yadav', 'UBT Chand',
       'DJ Jacobs', 'Sunny Singh', 'AL Menaria', 'AUK Pathan',
       'WD Parnell', 'JJ van der Wath', 'R Ninan', 'MS Wade',
       'JEC Franklin', 'TD Paine', 'SB Wagh', 'Shakib Al Hasan',
       'S Randiv', 'BJ Haddin', 'NLTC Perera', 'JE Taylor', 'NL McCullum',
       'RN ten Doeschate', 'TR Birt', 'M Klinger', 'Harpreet Singh',
       'Bipul Sharma', 'AC Blizzard', 'CA Ingram', 'S Nadeem',
       'DH Yagnik', 'KB Arun Karthik', 'AA Chavan', 'ND Doshi',
       'CJ Ferguson', 'Y Gnaneswara Rao', 'S Rana', 'BA Bhatt',
       'F du Plessis', 'RE Levi', 'DE Bollinger', 'SA Yadav',
       'MN Samuels', 'B Kumar', 'SPD Smith', 'GJ Maxwell', 'HV Patel',
       'DJ Harris', 'Ankit Sharma', 'SP Narine', 'JP Faulkner',
       'KK Cooper', 'GB Hogg', 'RR Bhatkal', 'CJ McKay', 'N Saini',
       'DA Miller', 'P Negi', 'Azhar Mahmood', 'AC Thomas', 'RJ Peterson',
       'A Ashish Reddy', 'V Pratap Singh', 'MJ Clarke', 'Gurkeerat Singh',
       'VR Aaron', 'AP Majumdar', 'PA Reddy', 'AD Russell', 'CA Lynn',
       'Sunny Gupta', 'MC Juneja', 'KK Nair', 'GH Vihari', 'MDKJ Perera',
       'B Laughlin', 'Mohammed Shami', 'BMAJ Mendis', 'M Vohra',
       'R Rampaul', 'P Awana', 'SMSM Senanayake', 'BJ Rohrer', 'KL Rahul',
       'J Syed Mohammad', 'BB Samantray', 'Q de Kock', 'R Dhawan',
       'MG Johnson', 'LJ Wright', 'AG Murtaza', 'IC Pandey',
       'X Thalaivan Sargunam', 'DJG Sammy', 'SV Samson', 'KW Richardson',
       'CH Morris', 'MM Sharma', 'CM Gautam', 'UA Birla', 'Parvez Rasool',
       'Sachin Baby', 'NM Coulter-Nile', 'CJ Anderson', 'NJ Maddinson',
       'AR Patel', 'JDS Neesham', 'PV Tambe', 'TG Southee', 'MA Starc',
       'BR Dunk', 'RR Rossouw', 'Shivam Sharma', 'LMP Simmons', 'VH Zol',
       'Imran Tahir', 'R Shukla', 'BCJ Cutting', 'BE Hendricks',
       'M de Lange', 'S Gopal', 'R Tewatia', 'JO Holder', 'JD Unadkat',
       'SS Iyer', 'DJ Hooda', 'SA Abbott', 'AN Ahmed', 'KS Williamson',
       'Iqbal Abdulla', 'SN Khan', 'D Wiese', 'HH Pandya',
       'MJ McClenaghan', 'Anureet Singh', 'DJ Muthuswami', 'PJ Cummins',
       'Karanveer Singh', 'Sandeep Sharma', 'J Suchith', 'JC Buttler',
       'CR Brathwaite', 'MP Stoinis', 'Ishan Kishan', 'C Munro',
       'AD Nath', 'MJ Guptill', 'P Sahu', 'TM Head', 'M Ashwin',
       'KH Pandya', 'NS Naik', 'RR Pant', 'SW Billings', 'KC Cariappa',
       'PSP Handscomb', 'Swapnil Singh', 'J Yadav', 'UT Khawaja',
       'HM Amla', 'JJ Bumrah', 'A Zampa', 'N Rana', 'S Kaushik',
       'F Behardien', 'KJ Abbott', 'ER Dwivedi', 'CJ Jordan', 'S Aravind',
       'YS Chahal', 'TS Mills', 'BA Stokes', 'JJ Roy', 'Vishnu Vinod',
       'CR Woakes', 'RA Tripathi', 'DL Chahar', 'V Shankar',
       'Rashid Khan', 'SN Thakur', 'C de Grandhomme', 'AF Milne',
       'S Badree', 'Mohammad Nabi', 'K Rabada', 'AJ Tye', 'Kuldeep Yadav',
       'SP Jackson', 'Ankit Soni', 'A Choudhary', 'AS Rajpoot',
       'Washington Sundar', 'E Lewis', 'MA Wood', 'RK Singh', 'DJM Short',
       'K Gowtham', 'S Kaul', 'Mujeeb Ur Rahman', 'Shivam Mavi',
       'Shubman Gill', 'TK Curran', 'TA Boult', 'H Klaasen', 'RK Bhui',
       'JC Archer', 'PP Shaw', 'LE Plunkett', 'M Markande',
       'Mustafizur Rahman', 'Basil Thampi', 'BB Sran', 'AD Hales',
       'MK Lomror', 'Mohammed Siraj', 'DR Shorey', 'MM Ali', 'P Chopra',
       'IS Sodhi', 'Abhishek Sharma', 'JPR Scantlebury-Searles',
       'SO Hetmyer', 'S Dube', 'NA Saini', 'JM Bairstow', 'KMA Paul',
       'N Pooran', 'P Ray Barman', 'S Lamichhane', 'SM Curran',
       'GC Viljoen', 'RD Chahar', 'M Prasidh Krishna', 'SD Lad',
       'R Parag', 'JL Denly', 'LS Livingstone', 'KK Ahmed', 'AJ Turner',
       'SE Rutherford', 'MJ Santner', 'P Simran Singh', 'JL Pattinson',
       'T Banton', 'D Padikkal', 'YBK Jaiswal', 'RD Gaikwad',
       'TU Deshpande', 'Abdul Samad', 'PK Garg', 'JR Philippe',
       'CV Varun', 'KL Nagarkoti', 'I Udana', 'Ravi Bishnoi', 'AT Carey',
       'N Jagadeesan', 'A Nortje', 'Kartik Tyagi', 'SS Cottrell',
       'Arshdeep Singh', 'DR Sams'], dtype=object)

In [ ]:
deliveries_2['player_dismissed'].isnull().unique()

array([ True, False])

In [ ]:
deliveries_2['player_dismissed']

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ...
193463    NaN
193464    NaN
193465    NaN
193466    NaN
193467    NaN
Name: player_dismissed, Length: 193468, dtype: object

In [ ]:
deliveries_2['player_dismissed'].fillna("none", inplace = True)

In [ ]:
deliveries_2['player_dismissed'].isnull().unique()

array([False])

In [ ]:
deliveries_2['player_dismissed']

0         none
1         none
2         none
3         none
4         none
          ...
193463    none
193464    none
193465    none
193466    none
193467    none
Name: player_dismissed, Length: 193468, dtype: object

In [ ]:
deliveries_2.columns

Index(['id', 'inning', 'over', 'ball', 'batsman', 'non_striker', 'bowler',
       'batsman_runs', 'extra_runs', 'total_runs', 'non_boundary', 'is_wicket',
       'dismissal_kind', 'player_dismissed', 'fielder', 'extras_type',
       'batting_team', 'bowling_team'],
      dtype='object')

In [ ]:
deliveries_2['fielder'].isnull().unique()

array([ True, False])

In [ ]:
deliveries_2['fielder'].unique()

array([nan, 'P Kumar', 'CL White', 'JH Kallis', 'M Kartik', 'RT Ponting',
       'WP Saha', 'AB Agarkar,WP Saha', 'BB McCullum', 'IK Pathan',
       'KC Sangakkara', 'Joginder Sharma', 'P Amarnath', 'PA Patel',
       'M Manhas', 'B Geeves', 'V Kohli', 'Z Khan', 'MV Boucher',
       'AM Nayar', 'L Ronchi', 'RG Sharma', 'SB Styris', 'AB Dinda',
       'DJ Hussey', 'SC Ganguly', 'Mohammad Hafeez,WP Saha', 'LR Shukla',
       'Mohammad Hafeez', 'A Symonds', 'PP Chawla', 'Kamran Akmal',
       'RA Jadeja,Kamran Akmal', 'MK Tiwary,KD Karthik', 'GD McGrath',
       'G Gambhir', 'AC Gilchrist', 'S Dhawan', 'KD Karthik', 'DJ Bravo',
       'S Badrinath', 'Harbhajan Singh', 'JDP Oram', 'SK Raina',
       'RA Jadeja', 'D Kalyankrishna', 'VVS Laxman,RP Singh', 'SB Bangar',
       'D Salunkhe', 'DS Kulkarni', 'DJ Bravo,L Ronchi', 'A Nehra',
       'Harbhajan Singh,L Ronchi', 'B Lee', 'RR Sarwan',
       'AM Rahane (sub)', 'Yuvraj Singh', 'M Rawat,SR Watson', 'MM Patel',
       'GC Smith', 'M Rawat', 'Sohail Tanvir,M Rawat', 'A Kumble',
       'MS Dhoni,Joginder Sharma', 'I Sharma', 'M Muralitharan',
       'PP Ojha', 'VVS Laxman', 'V Sehwag,R Bhatia',
       'DPMD Jayawardene,KC Sangakkara', 'W Jaffer,MV Boucher',
       'MS Dhoni', 'MEK Hussey', 'R Vinay Kumar (sub)', 'R Dravid',
       'SK Raina,MS Dhoni', 'Joginder Sharma,JDP Oram,MS Dhoni',
       'RV Uthappa', 'AM Rahane,ST Jayasuriya', 'PR Shah',
       'ST Jayasuriya', 'V Sehwag', 'LRPL Taylor', 'VY Mahesh', 'K Goel',
       'S Sreesanth', 'Yuvraj Singh,KC Sangakkara', 'SE Marsh',
       'SK Trivedi', 'M Kaif', 'RA Jadeja,M Rawat', 'Umar Gul,WP Saha',
       'SR Watson', 'T Kohli (sub)', 'Shoaib Malik', 'PJ Sangwan',
       'SP Goswami', 'DW Steyn', 'B Akhil', 'LPC Silva', 'W Jaffer',
       'R Vinay Kumar', 'B Chipli (sub)', 'AS Yadav', 'DB Ravi Teja',
       'DB Das,DJ Hussey', 'BJ Hodge', 'JR Hopes', 'SM Pollock',
       'AB de Villiers', 'DJ Thornely', 'SS Tiwary', 'Sohail Tanvir',
       'SK Warne', 'M Ntini', 'U Kaul', 'DPMD Jayawardene', 'DT Patil',
       'RP Singh', 'Shahid Afridi', 'HH Gibbs', 'YV Takawale',
       'YK Pathan', 'SA Asnodkar', 'MK Tiwary', 'CK Kapugedera',
       'DW Steyn,MV Boucher', 'M Rawat,Sohail Tanvir',
       'YV Takawale,CRD Fernando', 'SR Tendulkar', 'CRD Fernando',
       'JA Morkel', 'SP Fleming', 'S Vidyut', 'Salman Butt', 'A Chopra',
       'Niraj Patel', 'V Sehwag,KD Karthik', 'PP Chawla,U Kaul',
       'T Taibu', 'TM Dilshan,AB de Villiers', 'MF Maharoof',
       'LR Shukla,WP Saha', 'RR Raje', 'Younis Khan',
       'YK Pathan,SR Watson', 'WA Mota', 'TM Dilshan',
       'AB de Villiers (sub)', 'Shoaib Malik (sub)',
       'RV Uthappa,SM Pollock', 'LA Pomersbach', 'RR Powar',
       'Misbah-ul-Haq', 'MS Gony', 'R Bhatia', 'B Chipli',
       'CL White,SP Goswami', 'MF Maharoof,Shoaib Malik (sub),KD Karthik',
       'V Sehwag,MF Maharoof', 'DR Smith', 'Yuvraj Singh,PP Chawla',
       'TM Srivastava', 'TM Srivastava,DPMD Jayawardene,U Kaul',
       'VRV Singh', 'R Dravid,SP Goswami', 'SD Chitnis',
       'MS Dhoni,PA Patel', 'A Mukund', 'S Badrinath,PA Patel',
       'Sohail Tanvir,Kamran Akmal', 'T Kohli', 'RA Jadeja (sub)',
       'SB Bangar,SB Styris', 'Pankaj Singh', 'MK Pandey',
       'RR Raje,ST Jayasuriya', 'L Balaji', 'MS Gony,PA Patel',
       'TM Dilshan,KD Karthik', 'YK Pathan,M Rawat', 'M Ntini,MS Gony',
       'ML Hayden', 'T Thushara', 'R Ashwin', 'V Kohli,RV Uthappa',
       'JD Ryder', 'KD Karthik,DL Vettori', 'DL Vettori', 'DP Nannes',
       'MC Henriques', 'LR Shukla,BB McCullum', 'Harmeet Singh',
       'R Bishnoi', 'A Flintoff', 'A Chopra,BB McCullum', 'Yashpal Singh',
       'CH Gayle', 'Y Venugopal Rao', 'AC Gilchrist,Harmeet Singh',
       'KP Pietersen', 'KV Sharma,RV Uthappa', 'DA Warner (sub)',
       'V Sehwag,DL Vettori', 'PJ Sangwan,DP Nannes', 'AS Raut',
       'Kamran Khan,M Rawat', 'Kamran Khan', 'RS Bopara',
       'R Vinay Kumar,RV Uthappa', 'DJ Bravo,Z Khan', 'A Mishra',
       'RA Jadeja,SA Asnodkar', 'Shoaib Ahmed', 'BAW Mendis', 'AN Ghosh',
       'JP Duminy', 'MN van Wyk', 'DL Vettori,KD Karthik',
       'AD Mascarenhas', 'JP Duminy,PR Shah', 'SL Malinga',
       'RE van der Merwe,MV Boucher', 'SM Katich',
       'HH Gibbs,Y Venugopal Rao', 'AB de Villiers,KD Karthik',
       'VS Malik', 'M Vijay', 'SB Jakati', 'SM Harwood', 'NV Ojha',
       'DJ Bravo,PR Shah', 'RJ Harris', 'V Kohli,MV Boucher', 'M Morkel',
       'LA Carseldine', 'DA Warner,KD Karthik', 'DA Warner',
       'HH Gibbs,AC Gilchrist', 'DB Ravi Teja,AC Gilchrist',
       'SM Katich,KC Sangakkara', 'SL Malinga,Harbhajan Singh',
       'TL Suman,AC Gilchrist', 'AC Gilchrist,Y Venugopal Rao',
       'AD Mathews', 'B Akhil,P Kumar', 'RE van der Merwe',
       'M Muralitharan,MS Dhoni', 'S Tyagi', 'SK Warne,MM Patel',
       'AM Rahane', 'Harbhajan Singh,ST Jayasuriya',
       'KC Sangakkara,WA Mota', 'S Sohal', 'ML Hayden,MS Dhoni',
       'TL Suman', 'AB Agarkar,BJ Hodge', 'Mashrafe Mortaza',
       'LR Shukla (sub)', 'KC Sangakkara,B Lee', 'AM Salvi', 'SS Shaikh',
       'J Botha,YK Pathan', 'RJ Quiney', 'Mohammad Ashraful',
       'TM Dilshan,PJ Sangwan', 'MV Boucher,P Kumar', 'Anirudh Singh',
       'P Dogra', 'R Sathish', 'DPMD Jayawardene,PP Chawla', 'MS Bisla',
       'EJG Morgan', 'FY Fazal (sub)', 'G Gambhir,A Mishra',
       'A Mishra,KD Karthik', 'Y Nagar (sub)', 'AT Rayudu', 'AP Tare',
       'R Dravid,MV Boucher', 'JM Kemp', 'Bipul Sharma', 'CA Pujara',
       'AC Voges', 'AS Raut (sub)', 'AD Mathews,M Kartik', 'KA Pollard',
       'WPUJC Vaas', 'RP Singh,AC Gilchrist', 'ML Hayden,JA Morkel',
       'GJ Bailey (sub)', 'J Theron', 'KP Appanna (sub)', 'SJ Srivastava',
       'AA Jhunjhunwala', 'SW Tait', 'PP Chawla,IK Pathan', 'MJ Lumb',
       'FY Fazal', 'AA Jhunjhunwala,SK Warne', 'A Mishra,DP Nannes',
       'UT Yadav,KD Karthik', 'MS Dhoni,T Thushara', 'SB Jakati,MS Dhoni',
       'AC Voges,NV Ojha', 'R McLaren', 'JP Duminy (sub)',
       'SL Malinga,AT Rayudu', 'SK Raina,SB Jakati', 'S Ladda,KD Karthik',
       'KAJ Roach', 'MK Pandey,RV Uthappa', 'S Narwal', 'S Anirudha',
       'DE Bollinger', 'KA Pollard,AT Rayudu', 'M Kaif (sub)',
       'KP Appanna', 'PD Collingwood', 'AA Bilakhia', 'AP Dole',
       'S Badrinath,MS Dhoni', 'AA Jhunjhunwala,FY Fazal,NV Ojha',
       'R Bhatia,DL Vettori', 'Iqbal Abdulla', 'RP Singh,Harmeet Singh',
       'B Sumanth', 'MD Mishra', 'AB Agarkar', 'RV Uthappa,JH Kallis',
       'RS Sodhi', 'J Theron,KC Sangakkara', 'K Goel,KC Sangakkara',
       'SS Tiwary,AT Rayudu', 'S Dhawan (sub)',
       'ST Jayasuriya,Harbhajan Singh', 'RG Sharma,AC Gilchrist',
       'DW Steyn,RV Uthappa', 'KA Pollard,C Madan', 'AG Murtaza',
       'JH Kallis,R Vinay Kumar', 'AC Voges,Kamran Khan', 'UT Yadav',
       'JD Unadkat,BB McCullum', 'JD Unadkat', 'MR Marsh,R Sharma',
       'AM Nayar,KA Pollard', 'M Vijay,MS Dhoni,JA Morkel',
       'R Ashwin,MS Dhoni', 'S Ladda', 'AG Paunikar', 'J Botha',
       'AL Menaria', 'R Sathish,DJ Jacobs', 'DJ Jacobs', 'JEC Franklin',
       'R Sharma', 'Yuvraj Singh,RV Uthappa', 'RN ten Doeschate',
       'IR Jaggi', 'PC Valthaty', 'S Randiv', 'S Randiv,S Anirudha',
       'WD Parnell,RV Uthappa', 'RV Uthappa,NL McCullum (sub)',
       'WD Parnell', 'RV Gomez,RA Jadeja', 'DT Christian',
       'AG Paunikar,FY Fazal (sub)', 'MA Agarwal', 'R Ninan',
       'Sunny Singh', 'AJ Finch', 'SB Wagh,RV Uthappa', 'SB Wagh',
       'Shakib Al Hasan,MS Bisla', 'NLTC Perera', 'AC Thomas',
       'KM Jadhav', 'PA Patel,RA Jadeja', 'DH Yagnik',
       'STR Binny,SR Watson', 'AB de Villiers,S Aravind', 'Y Nagar',
       'A Symonds,AN Ahmed', 'KA Pollard,DJ Jacobs', 'STR Binny',
       'J Botha,DH Yagnik', 'KM Jadhav,PA Patel', 'NL McCullum',
       'A Mukund (sub)', 'A Mithun,AB de Villiers',
       'PA Patel,NLTC Perera', 'RV Gomez', 'SP Goswami,B Lee',
       'L Balaji,B Lee', 'Y Nagar,NV Ojha', 'Shakib Al Hasan (sub)',
       'Harpreet Singh', 'J Syed Mohammad', 'RA Jadeja,PA Patel',
       'SP Goswami,Iqbal Abdulla', 'YK Pathan,SP Goswami',
       'EJG Morgan,SP Goswami', 'DH Yagnik,SK Trivedi',
       'F du Plessis (sub)', 'CL White,KC Sangakkara', 'AC Blizzard',
       'PA Patel,R Vinay Kumar', 'S Ladda,JH Kallis',
       'AB Agarkar,NV Ojha', 'A Mithun', 'AUK Pathan',
       'R Bhatia,MV Boucher', 'TL Suman,AT Rayudu',
       'KB Arun Karthik (sub)', 'M Kaif,AB de Villiers', 'B Kumar',
       'WP Saha,R Ashwin', 'CJ Ferguson', 'Mandeep Singh,AC Gilchrist',
       'AB de Villiers,KB Arun Karthik', 'KB Arun Karthik',
       'Y Nagar,IK Pathan', 'DJ Hussey,AC Gilchrist',
       'DT Christian,Anand Rajan', 'Mandeep Singh', 'OA Shah',
       'RA Jadeja,BJ Hodge', 'AA Chavan', 'Y Gnaneswara Rao',
       'DT Christian,PP Ojha', 'MS Dhoni,DE Bollinger', 'Anand Rajan',
       'KH Devdhar', 'AN Ahmed', 'S Aravind', 'RG Sharma,DS Kulkarni',
       'AN Ahmed,KD Karthik', 'Harbhajan Singh,KD Karthik',
       'AJ Finch,NV Ojha', 'KD Karthik,KA Pollard', 'A Singh',
       'KK Cooper', 'JP Faulkner', 'KK Cooper,SP Goswami',
       'DAJ Bracewell', 'DAJ Bracewell,GJ Maxwell', 'HV Patel',
       'HV Patel,AB de Villiers', 'DJ Harris', 'Iqbal Abdulla,R Bhatia',
       'SPD Smith,M Kartik', 'SPD Smith,RV Uthappa',
       'IK Pathan,DPMD Jayawardene', 'KP Pietersen,NV Ojha',
       'V Sehwag,NV Ojha', 'F du Plessis,R Ashwin', 'RE Levi',
       'RR Bhatkal', 'F du Plessis', 'TM Dilshan (sub)', 'SPD Smith',
       'P Awana', 'S Nadeem', 'RA Jadeja,R Ashwin',
       'DJ Bravo,KMDN Kulasekara', 'G Gambhir,R Bhatia', 'DB Das',
       'T Mishra', 'AB de Villiers,R Vinay Kumar', 'BB McCullum,MS Bisla',
       'KMDN Kulasekara', 'N Saini', 'AD Mathews,RV Uthappa',
       'SE Marsh,PP Chawla', 'DA Miller', 'DA Miller,N Saini',
       'JH Kallis,R Bhatia', 'LA Pomersbach (sub)',
       'LJ Wright,RV Uthappa', 'Azhar Mahmood', 'DJ Harris (sub)',
       'NLTC Perera (sub)', 'DPMD Jayawardene,NV Ojha', 'P Dogra (sub)',
       'GB Hogg', 'B Lee,BB McCullum', 'A Mishra,PA Patel',
       'KP Appanna,AB de Villiers', 'R Vinay Kumar,AB de Villiers',
       'DA Miller (sub)', 'RJ Peterson', 'RA Jadeja,MS Dhoni',
       'Gurkeerat Singh', 'WP Saha (sub)', 'V Kohli,J Syed Mohammad',
       'BB McCullum,SP Narine', 'MJ Clarke', 'A Ashish Reddy,J Theron',
       'KP Appanna,SS Tiwary', 'DR Smith,KD Karthik',
       'S Anirudha,MS Dhoni', 'BB McCullum,R Bhatia', 'VR Aaron',
       'P Negi', 'Harbhajan Singh,DR Smith', 'A Chandila', 'CA Lynn',
       'UBT Chand', 'PJ Sangwan (sub)', 'RA Jadeja,SB Jakati',
       'DA Warner,NV Ojha', 'DJ Bravo,R Ashwin', 'Shakib Al Hasan',
       'MS Bisla,SP Narine', 'SP Narine', 'MG Johnson',
       'JD Unadkat,KB Arun Karthik', 'MR Marsh', 'MN Samuels',
       'R Vinay Kumar,KB Arun Karthik', 'Ankit Sharma', 'A Ashish Reddy',
       'R Shukla', 'Mohammed Shami,MS Bisla', 'BMAJ Mendis', 'R Dhawan',
       'CH Morris', 'DT Christian (sub)', 'KL Rahul', 'PA Reddy',
       'GH Vihari', 'AT Rayudu,PP Ojha', 'SV Samson',
       'AC Gilchrist,P Kumar', 'IK Pathan,M Morkel', 'BB Samantray',
       'Q de Kock', 'R Dravid,DH Yagnik', 'MG Johnson,PP Ojha',
       'SK Raina,RA Jadeja', 'BMAJ Mendis,KM Jadhav',
       'PA Reddy,NLTC Perera', 'I Sharma,Q de Kock', 'DJ Bravo,MS Dhoni',
       'MM Sharma', 'SMSM Senanayake', 'R Rampaul', 'AD Russell',
       'M Vohra', 'S Kaul', 'BJ Rohrer', 'BB McCullum (sub)', 'DJG Sammy',
       'JH Kallis,MS Bisla', 'AB de Villiers,J Syed Mohammad',
       'DB Das,L Balaji', 'LJ Wright', 'JP Faulkner,SV Samson',
       'V Kohli,AB de Villiers', 'JA Morkel,R Ashwin', 'KV Sharma',
       'R Sathish,Gurkeerat Singh', 'M Muralitharan,KB Arun Karthik',
       'GH Vihari,DJG Sammy', 'P Suyal', 'UA Birla', 'Sachin Baby',
       'RG Sharma,KD Karthik', 'L Balaji,MS Bisla', 'JO Holder',
       'K Upadhyay', 'BJ Rohrer,KM Jadhav', 'R Sathish,Harmeet Singh',
       'I Sharma,DJG Sammy', 'NLTC Perera,PA Patel', 'MS Bisla,JH Kallis',
       'AG Murtaza,RV Uthappa', 'LJ Wright,RV Uthappa,AD Mathews',
       'SR Watson,JP Faulkner,DH Yagnik', 'GJ Maxwell',
       'STR Binny,Sachin Baby,KK Cooper', 'GJ Maxwell,KD Karthik',
       'NM Coulter-Nile', 'BB Samantray,PA Patel', 'EJG Morgan,MS Bisla',
       'AM Rahane,JP Faulkner', 'R Shukla (sub),DH Yagnik',
       'MM Sharma,CH Morris', 'AR Patel (sub)', 'CJ Anderson',
       'GJ Bailey', 'KW Richardson', 'YS Chahal', 'S Rana',
       'NJ Maddinson', 'WD Parnell (sub)', 'Mohammed Shami', 'AR Patel',
       'BW Hilfenhaus', 'MA Starc', 'CM Gautam', 'AM Rahane,SV Samson',
       'YV Takawale,PA Patel', 'TG Southee', 'S Nadeem,Mohammed Shami',
       'AV Wankhade (sub)', 'IC Pandey', 'MK Pandey,MS Bisla', 'SA Yadav',
       'SPD Smith,SV Samson', 'KK Nair', 'BR Dunk',
       'MS Dhoni,BW Hilfenhaus', 'MC Henriques (sub)',
       'SK Raina,RA Jadeja,MM Sharma', 'PA Patel,MA Starc', 'LMP Simmons',
       'P Kumar,CM Gautam', 'SA Yadav,RV Uthappa', 'RR Rossouw (sub)',
       'RG Sharma,CM Gautam', 'MS Dhoni,BB McCullum',
       'R Shukla,Q de Kock', 'Shivam Sharma', 'M Vohra,Sandeep Sharma',
       'BCJ Cutting', 'NV Ojha,DJG Sammy', 'K Santokie', 'BE Hendricks',
       'Parvez Rasool', 'Yuvraj Singh,PA Patel', 'Sandeep Sharma',
       'V Kohli,YV Takawale', 'SK Raina,P Negi', 'KD Karthik,KM Jadhav',
       'Karanveer Singh', 'RV Uthappa,R Vinay Kumar',
       'R Dhawan,GJ Bailey', 'KK Nair,SV Samson', 'PP Chawla,RV Uthappa',
       'BR Dunk (sub)', 'GJ Maxwell,WP Saha', 'SS Iyer',
       'MS Dhoni,A Nehra', 'TA Boult', 'M Morkel,Shakib Al Hasan',
       'KD Karthik,VR Aaron', 'J Suchith', 'KS Williamson', 'RG More',
       'PJ Cummins', 'Anureet Singh', 'RN ten Doeschate,RV Uthappa',
       'RG Sharma,KA Pollard', 'MS Bisla,AN Ahmed', 'Imran Tahir',
       'R Tewatia', 'RR Rossouw', 'DR Smith,MS Dhoni', 'J Yadav (sub)',
       'HV Patel,V Kohli', 'D Wiese', 'HH Pandya (sub)',
       'GH Vihari,NV Ojha', 'JP Duminy,KM Jadhav', 'DJ Hooda',
       'DJ Hooda,SV Samson', 'TG Southee,SV Samson',
       'KA Pollard,R Vinay Kumar', 'B Aparajith (sub)',
       'J Suchith,R Vinay Kumar', 'P Negi,MS Dhoni',
       'G Gambhir,RN ten Doeschate', 'Bipul Sharma,NV Ojha', 'HH Pandya',
       'J Yadav', 'V Kohli,KD Karthik', 'Shakib Al Hasan,Azhar Mahmood',
       'HH Pandya,KA Pollard', 'MJ McClenaghan,PA Patel',
       'UBT Chand (sub)', 'STR Binny,JP Faulkner', 'YS Chahal,KD Karthik',
       'SN Khan', 'AF Milne', 'GB Hogg,RV Uthappa', 'C Munro',
       'TG Southee,PA Patel', 'CR Brathwaite', 'Z Khan,KK Nair,Q de Kock',
       'Shakib Al Hasan,RV Uthappa', 'KD Karthik,DJ Bravo',
       'MC Henriques,NV Ojha', 'AD Russell,RV Uthappa',
       'Harbhajan Singh,PA Patel', 'KH Pandya',
       'P Negi,CH Morris,Q de Kock', 'SS Iyer,Q de Kock',
       'Mustafizur Rahman', 'NS Naik', 'DA Miller,NS Naik',
       'SS Tiwary,MS Dhoni', 'JC Buttler', 'PV Tambe', 'BB Sran',
       'KW Richardson,KL Rahul', 'GJ Maxwell,MP Stoinis',
       'JP Faulkner,KD Karthik', 'Ishan Kishan', 'KC Cariappa', 'RR Pant',
       'SW Billings,Q de Kock', 'GJ Maxwell,Sandeep Sharma',
       'R Sathish (sub)', 'WP Saha,Sandeep Sharma',
       'R Sathish (sub),RV Uthappa', 'AM Rahane,MS Dhoni', 'SW Billings',
       'V Shankar (sub)', 'SR Watson,STR Binny', 'Z Khan,Q de Kock',
       'DA Miller,WP Saha', 'BB Sran,Yuvraj Singh', 'DJ Hooda,NV Ojha',
       'AT Rayudu,JC Buttler', 'Harbhajan Singh,KH Pandya', 'JJ Bumrah',
       'SR Watson,Iqbal Abdulla', 'UT Khawaja', 'CJ Jordan',
       'SR Watson,Sachin Baby', 'ER Dwivedi', 'AS Rajpoot,RV Uthappa',
       'KK Nair,Q de Kock', 'DL Chahar', 'F Behardien',
       'Shakib Al Hasan,Kuldeep Yadav', 'YS Chahal,KL Rahul',
       'Sachin Baby,KL Rahul', 'Kuldeep Yadav', 'CJ Jordan (sub)',
       'MS Dhoni,AB Dinda', 'N Rana', 'MP Stoinis', 'BA Stokes',
       'B Stanlake', 'Rashid Khan', 'MJ McClenaghan', 'R Dhawan (sub)',
       'CR Woakes', 'RD Chahar', 'C de Grandhomme', 'JJ Roy',
       'V Kohli,KM Jadhav', 'RA Tripathi', 'C de Grandhomme,RV Uthappa',
       'P Negi,KM Jadhav', 'V Shankar (sub),Yuvraj Singh',
       'BB McCullum,KD Karthik', 'K Rabada', 'KK Nair,RR Pant',
       'Basil Thampi', 'TS Mills', 'S Badree', 'Washington Sundar',
       'JD Unadkat,BA Stokes', 'SN Thakur', 'SN Thakur,MS Dhoni',
       'SP Jackson,G Gambhir', 'MA Agarwal (sub)', 'LH Ferguson,MS Dhoni',
       'NM Coulter-Nile,RV Uthappa', 'TM Head', 'Ankit Soni',
       'Mohammed Siraj', 'SP Jackson', 'R Powell (sub)',
       'SPD Smith,DT Christian', 'CR Brathwaite (sub)', 'MJ Guptill',
       'DA Warner,B Kumar', 'V Shankar', 'AR Patel,WP Saha',
       'A Mishra,Mohammed Shami', 'J Suchith (sub)', 'SS Iyer,Z Khan',
       'Vishnu Vinod', 'AS Rajpoot', 'J Suchith (sub),PA Patel',
       'DT Christian,SN Thakur', 'MA Wood', 'E Lewis', 'AJ Tye',
       'RK Singh', 'B Laughlin', 'Shivam Mavi (sub)', 'K Gowtham',
       'Mujeeb Ur Rahman', 'DJM Short', 'AP Tare (sub)', 'Shivam Mavi',
       'MK Tiwary (sub)', 'TK Curran', 'H Klaasen', 'LE Plunkett',
       'Avesh Khan', 'DJ Hooda (sub)', 'PP Shaw', 'M Markande',
       'AD Hales', 'Shubman Gill', 'DJ Willey', 'RK Singh (sub)',
       'AD Nath', 'JPR Scantlebury-Searles', 'M Prasidh Krishna',
       'RD Chahar (sub)', 'Abhishek Sharma', 'MM Ali', 'R Tewatia (sub)',
       'JC Archer', 'DR Shorey (sub)', 'S Dube', 'Rasikh Salam',
       'KK Nair (sub)', 'SO Hetmyer', 'NA Saini', 'P Chopra (sub)',
       'M Ashwin', 'JM Bairstow', 'Mohammad Nabi', 'H Klaasen (sub)',
       'SM Curran', 'S Lamichhane', 'CA Ingram', 'S Midhun', 'S Gopal',
       'KMA Paul', 'Milind Kumar (sub)', 'N Pooran', 'SE Rutherford',
       'R Parag', 'MJ Santner', 'P Simran Singh', 'LS Livingstone',
       'MK Lomror', 'O Thomas', 'S Sandeep Warrier',
       'Anmolpreet Singh (sub)', 'JL Pattinson', 'D Padikkal', 'PK Garg',
       'TU Deshpande', 'KL Nagarkoti', 'KK Ahmed', 'YBK Jaiswal',
       'I Udana', 'JDS Neesham', 'CV Varun', 'RD Gaikwad', 'AT Carey',
       'A Nortje', 'Ravi Bishnoi', 'AS Roy (sub)', 'Abdul Samad',
       'Shahbaz Ahmed', 'CJ Green (sub)', 'PK Garg (sub)',
       'SP Goswami (sub)', 'T Natarajan', 'Arshdeep Singh',
       'Lalit Yadav (sub)', 'Kartik Tyagi', 'DR Sams', 'P Negi (sub)',
       'A Zampa', 'KMA Paul (sub)', 'P Dubey'], dtype=object)

In [ ]:
deliveries_2['fielder'].fillna("none", inplace = True)

In [ ]:
deliveries_2['fielder'].isnull().unique()

array([False])

In [ ]:
deliveries_2['extras_type'].unique()

array([nan, 'byes', 'wides', 'legbyes', 'noballs', 'penalty'],
      dtype=object)

In [ ]:
deliveries_2['extras_type'].fillna("none", inplace = True)

In [ ]:
deliveries_2['extras_type'].unique()

array(['none', 'byes', 'wides', 'legbyes', 'noballs', 'penalty'],
      dtype=object)

In [ ]:
deliveries_2['batting_team'].unique()

array(['Kolkata', 'Bangalore', 'Punjab', 'Chennai', 'Rajasthan', 'Delhi',
       'Mumbai', 'Hyderabad', 'Kerala', 'Pune', 'Gujarat'], dtype=object)

In [ ]:
deliveries_2['bowling_team'].unique()

array(['Bangalore', 'Kolkata', 'Chennai', 'Punjab', 'Delhi', 'Rajasthan',
       'Mumbai', 'Hyderabad', 'Kerala', 'Pune', 'Unknown', 'Gujarat'],
      dtype=object)

In [ ]:
deliveries_2.head()

       id  inning  over  ball  ... fielder extras_type batting_team  bowling_team
0  335982       1     6     5  ...    none        none      Kolkata     Bangalore
1  335982       1     6     6  ...    none        none      Kolkata     Bangalore
2  335982       1     7     1  ...    none        none      Kolkata     Bangalore
3  335982       1     7     2  ...    none        none      Kolkata     Bangalore
4  335982       1     7     3  ...    none        none      Kolkata     Bangalore

[5 rows x 18 columns]

In [ ]:
matches_2.head()

       id        city        date  ...  method    umpire1         umpire2
0  335982   Bangalore  2008-04-18  ...  Normal  Asad Rauf     RE Koertzen
1  335983  Chandigarh  2008-04-19  ...  Normal  MR Benson      SL Shastri
2  335984       Delhi  2008-04-19  ...  Normal  Aleem Dar  GA Pratapkumar
3  335985      Mumbai  2008-04-20  ...  Normal   SJ Davis       DJ Harper
4  335986     Kolkata  2008-04-20  ...  Normal  BF Bowden     K Hariharan

[5 rows x 17 columns]

In [ ]:
matches_2['result'].unique()

array(['runs', 'wickets', 'tie', nan], dtype=object)

In [ ]:
matches_2['result'].fillna("No Result", inplace = True)

In [ ]:
matches_2['result'].unique()

array(['runs', 'wickets', 'tie', 'No Result'], dtype=object)

In [ ]:
Merge = pd.merge(deliveries_2,matches_2,on='id',how='inner')
Merge.head(10)

       id  inning  over  ball  ... eliminator  method    umpire1      umpire2
0  335982       1     6     5  ...         No  Normal  Asad Rauf  RE Koertzen
1  335982       1     6     6  ...         No  Normal  Asad Rauf  RE Koertzen
2  335982       1     7     1  ...         No  Normal  Asad Rauf  RE Koertzen
3  335982       1     7     2  ...         No  Normal  Asad Rauf  RE Koertzen
4  335982       1     7     3  ...         No  Normal  Asad Rauf  RE Koertzen
5  335982       1     7     4  ...         No  Normal  Asad Rauf  RE Koertzen
6  335982       1     7     5  ...         No  Normal  Asad Rauf  RE Koertzen
7  335982       1     7     6  ...         No  Normal  Asad Rauf  RE Koertzen
8  335982       1     8     1  ...         No  Normal  Asad Rauf  RE Koertzen
9  335982       1     8     2  ...         No  Normal  Asad Rauf  RE Koertzen

[10 rows x 34 columns]

In [ ]:
Merge.head(10)

       id  inning  over  ball  ... eliminator  method    umpire1      umpire2
0  335982       1     6     5  ...         No  Normal  Asad Rauf  RE Koertzen
1  335982       1     6     6  ...         No  Normal  Asad Rauf  RE Koertzen
2  335982       1     7     1  ...         No  Normal  Asad Rauf  RE Koertzen
3  335982       1     7     2  ...         No  Normal  Asad Rauf  RE Koertzen
4  335982       1     7     3  ...         No  Normal  Asad Rauf  RE Koertzen
5  335982       1     7     4  ...         No  Normal  Asad Rauf  RE Koertzen
6  335982       1     7     5  ...         No  Normal  Asad Rauf  RE Koertzen
7  335982       1     7     6  ...         No  Normal  Asad Rauf  RE Koertzen
8  335982       1     8     1  ...         No  Normal  Asad Rauf  RE Koertzen
9  335982       1     8     2  ...         No  Normal  Asad Rauf  RE Koertzen

[10 rows x 34 columns]

In [ ]:
Merge.dtypes

id                    int64
inning                int64
over                  int64
ball                  int64
batsman              object
non_striker          object
bowler               object
batsman_runs          int64
extra_runs            int64
total_runs            int64
non_boundary          int64
is_wicket             int64
dismissal_kind       object
player_dismissed     object
fielder              object
extras_type          object
batting_team         object
bowling_team         object
city                 object
date                 object
player_of_match      object
venue                object
neutral_venue         int64
team1                object
team2                object
toss_winner          object
toss_decision        object
winner               object
result               object
result_margin       float64
eliminator           object
method               object
umpire1              object
umpire2              object
dtype: object

In [ ]:
Merge['result_margin'].unique()

array([140.,  33.,   9.,   5.,   6.,   3.,  66.,   7.,  10.,   4.,  13.,
        45.,   8.,  29.,  18.,  23.,  41.,  12.,  65.,  25.,   1.,  14.,
       105.,  19.,  75.,  92.,  11.,  24.,   0.,  27.,  38.,  78.,  16.,
        53.,   2.,  31.,  55.,  98.,  34.,  36.,  39.,  17.,  40.,  67.,
        63.,  37.,  57.,  35.,  22.,  21.,  48.,  26.,  20.,  85.,  32.,
        76., 111.,  82.,  43.,  58.,  28.,  74.,  42.,  59.,  46.,  47.,
        86.,  44.,  87., 130.,  15.,  60.,  77.,  30.,  50.,  93.,  72.,
        62.,  97., 138.,  71., 144.,  80.,  51.,  61., 146.,  64., 102.,
       118.,  49.,  88.,  69.])

In [ ]:
Merge['eliminator'].unique()

array(['No', 'Yes', 'NR'], dtype=object)

In [ ]:
Merge[Merge.isna().any(axis=1)]

Empty DataFrame
Columns: [id, inning, over, ball, batsman, non_striker, bowler, batsman_runs, extra_runs, total_runs, non_boundary, is_wicket, dismissal_kind, player_dismissed, fielder, extras_type, batting_team, bowling_team, city, date, player_of_match, venue, neutral_venue, team1, team2, toss_winner, toss_decision, winner, result, result_margin, eliminator, method, umpire1, umpire2]
Index: []

In [ ]:
Merge.head()

       id  inning  over  ball  ... eliminator  method    umpire1      umpire2
0  335982       1     6     5  ...         No  Normal  Asad Rauf  RE Koertzen
1  335982       1     6     6  ...         No  Normal  Asad Rauf  RE Koertzen
2  335982       1     7     1  ...         No  Normal  Asad Rauf  RE Koertzen
3  335982       1     7     2  ...         No  Normal  Asad Rauf  RE Koertzen
4  335982       1     7     3  ...         No  Normal  Asad Rauf  RE Koertzen

[5 rows x 34 columns]

In [ ]:
Merge.dtypes

id                    int64
inning                int64
over                  int64
ball                  int64
batsman              object
non_striker          object
bowler               object
batsman_runs          int64
extra_runs            int64
total_runs            int64
non_boundary          int64
is_wicket             int64
dismissal_kind       object
player_dismissed     object
fielder              object
extras_type          object
batting_team         object
bowling_team         object
city                 object
date                 object
player_of_match      object
venue                object
neutral_venue         int64
team1                object
team2                object
toss_winner          object
toss_decision        object
winner               object
result               object
result_margin       float64
eliminator           object
method               object
umpire1              object
umpire2              object
dtype: object

In [ ]:
Merge['umpire2'].unique()

array(['RE Koertzen', 'SL Shastri', 'GA Pratapkumar', 'DJ Harper',
       'K Hariharan', 'RB Tiffin', 'AM Saheba', 'MR Benson', 'IL Howell',
       'AV Jayaprakash', 'I Shivram', 'BR Doctrove', 'BG Jerling',
       'SJ Davis', 'SD Ranade', 'SJA Taufel', 'M Erasmus',
       'TH Wijewardene', 'SK Tarapore', 'S Ravi', 'HDPK Dharmasena',
       'SS Hazare', 'PR Reiffel', 'AL Hill', 'RJ Tucker', 'VA Kulkarni',
       'JD Cloete', 'BNJ Oxenford', 'S Asnani', 'S Das', 'C Shamshuddin',
       'AK Chaudhary', 'K Srinath', 'Subroto Das', 'CK Nandan',
       'NJ Llong', 'RK Illingworth', 'PG Pathak', 'CB Gaffaney',
       'K Srinivasan', 'SD Fry', 'VK Sharma', 'A Nand Kishore',
       'Nitin Menon', 'A Deshmukh', 'YC Barde', 'IJ Gould'], dtype=object)

In [ ]:
Merge.dtypes

id                    int64
inning                int64
over                  int64
ball                  int64
batsman              object
non_striker          object
bowler               object
batsman_runs          int64
extra_runs            int64
total_runs            int64
non_boundary          int64
is_wicket             int64
dismissal_kind       object
player_dismissed     object
fielder              object
extras_type          object
batting_team         object
bowling_team         object
city                 object
date                 object
player_of_match      object
venue                object
neutral_venue         int64
team1                object
team2                object
toss_winner          object
toss_decision        object
winner               object
result               object
result_margin       float64
eliminator           object
method               object
umpire1              object
umpire2              object
dtype: object

In [ ]:
Merge['batsman'] = pd.Series(Merge['batsman'], dtype="string")
Merge['non_striker'] = pd.Series(Merge['non_striker'], dtype="string")
Merge['bowler'] = pd.Series(Merge['bowler'], dtype="string")
Merge['dismissal_kind'] = pd.Series(Merge['dismissal_kind'], dtype="string")
Merge['player_dismissed'] = pd.Series(Merge['player_dismissed'], dtype="string")
Merge['fielder'] = pd.Series(Merge['fielder'], dtype="string")
Merge['extras_type'] = pd.Series(Merge['extras_type'], dtype="string")
Merge['batting_team'] = pd.Series(Merge['batting_team'], dtype="string")
Merge['bowling_team'] = pd.Series(Merge['bowling_team'], dtype="string")
Merge['city'] = pd.Series(Merge['city'], dtype="string")
Merge['date'] = pd.Series(Merge['date'], dtype="string")
Merge['player_of_match'] = pd.Series(Merge['player_of_match'], dtype="string")
Merge['venue'] = pd.Series(Merge['venue'], dtype="string")
Merge['team1'] = pd.Series(Merge['team1'], dtype="string")
Merge['team2'] = pd.Series(Merge['team2'], dtype="string")
Merge['toss_winner'] = pd.Series(Merge['toss_winner'], dtype="string")
Merge['toss_decision'] = pd.Series(Merge['toss_decision'], dtype="string")
Merge['winner'] = pd.Series(Merge['winner'], dtype="string")
Merge['result'] = pd.Series(Merge['result'], dtype="string")
Merge['eliminator'] = pd.Series(Merge['eliminator'], dtype="string")
Merge['method'] = pd.Series(Merge['method'], dtype="string")
Merge['umpire1'] = pd.Series(Merge['umpire1'], dtype="string")
Merge['umpire2'] = pd.Series(Merge['umpire2'], dtype="string")

In [ ]:
Merge.dtypes

id                    int64
inning                int64
over                  int64
ball                  int64
batsman              string
non_striker          string
bowler               string
batsman_runs          int64
extra_runs            int64
total_runs            int64
non_boundary          int64
is_wicket             int64
dismissal_kind       string
player_dismissed     string
fielder              string
extras_type          string
batting_team         string
bowling_team         string
city                 string
date                 string
player_of_match      string
venue                string
neutral_venue         int64
team1                string
team2                string
toss_winner          string
toss_decision        string
winner               string
result               string
result_margin       float64
eliminator           string
method               string
umpire1              string
umpire2              string
dtype: object

In [ ]:
Merge.head()

       id  inning  over  ball  ... eliminator  method    umpire1      umpire2
0  335982       1     6     5  ...         No  Normal  Asad Rauf  RE Koertzen
1  335982       1     6     6  ...         No  Normal  Asad Rauf  RE Koertzen
2  335982       1     7     1  ...         No  Normal  Asad Rauf  RE Koertzen
3  335982       1     7     2  ...         No  Normal  Asad Rauf  RE Koertzen
4  335982       1     7     3  ...         No  Normal  Asad Rauf  RE Koertzen

[5 rows x 34 columns]

In [ ]:
Merge[Merge.isna().any(axis=1)]

Empty DataFrame
Columns: [id, inning, over, ball, batsman, non_striker, bowler, batsman_runs, extra_runs, total_runs, non_boundary, is_wicket, dismissal_kind, player_dismissed, fielder, extras_type, batting_team, bowling_team, city, date, player_of_match, venue, neutral_venue, team1, team2, toss_winner, toss_decision, winner, result, result_margin, eliminator, method, umpire1, umpire2]
Index: []

In [ ]:
Merge['venue'].unique()

<StringArray>
[                           'M.Chinnaswamy Stadium',
       'Punjab Cricket Association Stadium, Mohali',
                                 'Feroz Shah Kotla',
                                 'Wankhede Stadium',
                                     'Eden Gardens',
                           'Sawai Mansingh Stadium',
        'Rajiv Gandhi International Stadium, Uppal',
                  'MA Chidambaram Stadium, Chepauk',
                       'Dr DY Patil Sports Academy',
                                         'Newlands',
                                 "St George's Park",
                                        'Kingsmead',
                                  'SuperSport Park',
                                     'Buffalo Park',
                            'New Wanderers Stadium',
                            'De Beers Diamond Oval',
                                  'OUTsurance Oval',
                                'Brabourne Stadium',
                     'Sardar Patel Stadium, Motera',
                                 'Barabati Stadium',
     'Vidarbha Cricket Association Stadium, Jamtha',
     'Himachal Pradesh Cricket Association Stadium',
                                    'Nehru Stadium',
                           'Holkar Cricket Stadium',
              'DYSRR International Cricket Stadium',
                       'Subrata Roy Sahara Stadium',
 'Shaheed Veer Narayan Singh International Stadium',
               'JSCA International Stadium Complex',
                             'Sheikh Zayed Stadium',
                          'Sharjah Cricket Stadium',
              'Dubai International Cricket Stadium',
          'Maharashtra Cricket Association Stadium',
     'Punjab Cricket Association IS Bindra Stadium',
           'Saurashtra Cricket Association Stadium',
                                       'Green Park']
Length: 35, dtype: string

In [ ]:
# from google.colab import files
# Merge.to_csv('Merged_Deliveries_and_Matches.csv')
# files.download('Merged_Deliveries_and_Matches.csv')

In [ ]:
from google.colab import files
matches_2.to_csv('Matches_After_Cleaning.csv')
files.download('Matches_After_Cleaning.csv')

In [ ]:
from google.colab import files
deliveries_2.to_csv('Deliveries_After_Cleaning.csv')
files.download('Deliveries_After_Cleaning.csv')

# Now Exporting the final Dataset

In [ ]:

from google.colab import files
Merge.to_csv('Merged_Deliveries_and_Matches.csv')
files.download('Merged_Deliveries_and_Matches.csv')